# Generated by Django 4.2 on 2023-08-24 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "tom_nonlocalizedevents",
            "0017_alter_eventsequence_external_coincidence_and_more",
        ),
        ("tom_surveys", "0004_alter_surveyobservationrecord_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreasureMapPointing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("treasuremap_id", models.IntegerField(null=True, unique=True)),
                ("status", models.CharField(max_length=200)),
                (
                    "nonlocalizedevent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treasuremap_pointings",
                        to="tom_nonlocalizedevents.nonlocalizedevent",
                    ),
                ),
                (
                    "observation_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treasuremap_pointings",
                        to="tom_surveys.surveyobservationrecord",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="treasuremappointing",
            constraint=models.UniqueConstraint(
                fields=("nonlocalizedevent", "observation_record"),
                name="unique_nonlocalizedevent_observation_record",
            ),
        ),
    ]
