# Generated by Django 4.2 on 2023-08-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tom_treasuremap", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="treasuremappointing",
            name="unique_nonlocalizedevent_observation_record",
        ),
        migrations.AlterField(
            model_name="treasuremappointing",
            name="treasuremap_id",
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="treasuremappointing",
            constraint=models.UniqueConstraint(
                fields=("nonlocalizedevent", "observation_record", "status"),
                name="unique_nonlocalizedevent_observation_record_status",
            ),
        ),
    ]
