# Generated by Django 4.2.16 on 2025-01-06 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_treasuremap', '0002_remove_treasuremappointing_unique_nonlocalizedevent_observation_record_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treasuremappointing',
            options={'ordering': ['-observation_record__scheduled_start']},
        ),
    ]
