# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.

from django.db import models
from django.contrib.postgres.fields import ArrayField
from tom_nonlocalizedevents.models import EventCandidate, Target


class AsassnQ3C(models.Model):
    aid = models.AutoField(primary_key=True)
    asassn_id = models.CharField(max_length=40, blank=True, null=True)
    source_id = models.CharField(max_length=20, blank=True, null=True)
    asassn_name = models.CharField(max_length=30, blank=True, null=True)
    other_names = models.CharField(max_length=32, blank=True, null=True)
    ra = models.FloatField(blank=True, null=True)
    dec = models.FloatField(blank=True, null=True)
    l = models.FloatField(blank=True, null=True)
    b = models.FloatField(blank=True, null=True)
    mean_vmag = models.FloatField(blank=True, null=True)
    amplitude = models.FloatField(blank=True, null=True)
    period = models.FloatField(blank=True, null=True)
    variable_type = models.CharField(max_length=10, blank=True, null=True)
    class_probability = models.FloatField(blank=True, null=True)
    lksl_statistic = models.FloatField(blank=True, null=True)
    rfr_score = models.FloatField(blank=True, null=True)
    epoch_hjd = models.FloatField(blank=True, null=True)
    gdr2_id = models.BigIntegerField(blank=True, null=True)
    phot_g_mean_mag = models.FloatField(blank=True, null=True)
    e_phot_g_mean_mag = models.FloatField(blank=True, null=True)
    phot_bp_mean_mag = models.FloatField(blank=True, null=True)
    e_phot_bp_mean_mag = models.FloatField(blank=True, null=True)
    phot_rp_mean_mag = models.FloatField(blank=True, null=True)
    e_phot_rp_mean_mag = models.FloatField(blank=True, null=True)
    bp_rp = models.FloatField(blank=True, null=True)
    parallax = models.FloatField(blank=True, null=True)
    parallax_error = models.FloatField(blank=True, null=True)
    parallax_over_error = models.FloatField(blank=True, null=True)
    pmra = models.FloatField(blank=True, null=True)
    pmra_error = models.FloatField(blank=True, null=True)
    pmdec = models.FloatField(blank=True, null=True)
    pmdec_error = models.FloatField(blank=True, null=True)
    vt = models.FloatField(blank=True, null=True)
    dist = models.FloatField(blank=True, null=True)
    allwise_id = models.CharField(max_length=20, blank=True, null=True)
    j_mag = models.FloatField(blank=True, null=True)
    e_j_mag = models.FloatField(blank=True, null=True)
    h_mag = models.FloatField(blank=True, null=True)
    e_h_mag = models.FloatField(blank=True, null=True)
    k_mag = models.FloatField(blank=True, null=True)
    e_k_mag = models.FloatField(blank=True, null=True)
    w1_mag = models.FloatField(blank=True, null=True)
    e_w1_mag = models.FloatField(blank=True, null=True)
    w2_mag = models.FloatField(blank=True, null=True)
    e_w2_mag = models.FloatField(blank=True, null=True)
    w3_mag = models.FloatField(blank=True, null=True)
    e_w3_mag = models.FloatField(blank=True, null=True)
    w4_mag = models.FloatField(blank=True, null=True)
    e_w4_mag = models.FloatField(blank=True, null=True)
    j_k = models.FloatField(blank=True, null=True)
    w1_w2 = models.FloatField(blank=True, null=True)
    w3_w4 = models.FloatField(blank=True, null=True)
    apass_dr9_id = models.BigIntegerField(blank=True, null=True)
    apass_vmag = models.FloatField(blank=True, null=True)
    e_apass_vmag = models.FloatField(blank=True, null=True)
    apass_bmag = models.FloatField(blank=True, null=True)
    e_apass_bmag = models.FloatField(blank=True, null=True)
    apass_gpmag = models.FloatField(blank=True, null=True)
    e_apass_gpmag = models.FloatField(blank=True, null=True)
    apass_rpmag = models.FloatField(blank=True, null=True)
    e_apass_rpmag = models.FloatField(blank=True, null=True)
    apass_ipmag = models.FloatField(blank=True, null=True)
    e_apass_ipmag = models.FloatField(blank=True, null=True)
    b_v = models.FloatField(blank=True, null=True)
    e_b_v = models.FloatField(blank=True, null=True)
    vector_x = models.FloatField(blank=True, null=True)
    vector_y = models.FloatField(blank=True, null=True)
    vector_z = models.FloatField(blank=True, null=True)
    reference = models.CharField(max_length=45, blank=True, null=True)
    periodic = models.BooleanField(blank=True, null=True)
    classified = models.BooleanField(blank=True, null=True)
    asassn_discovery = models.BooleanField(blank=True, null=True)
    created_at = models.DateTimeField(blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True)
    edr3_source_id = models.CharField(max_length=25, blank=True, null=True)
    galex_id = models.CharField(max_length=25, blank=True, null=True)
    fuvmag = models.FloatField(blank=True, null=True)
    e_fuvmag = models.FloatField(blank=True, null=True)
    nuvmag = models.FloatField(blank=True, null=True)
    e_nuvmag = models.FloatField(blank=True, null=True)
    tic_id = models.CharField(max_length=16, blank=True, null=True)
    pm = models.FloatField(blank=True, null=True)
    ruwe = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "asassn_q3c"


class Cosmicflows4Q3C(models.Model):
    cid = models.AutoField(primary_key=True)
    recno = models.IntegerField(blank=True, null=True)
    name = models.CharField(max_length=64, blank=True, null=True)
    raj2000 = models.FloatField(blank=True, null=True)
    dej2000 = models.FloatField(blank=True, null=True)
    dist = models.FloatField(blank=True, null=True)
    z = models.FloatField(blank=True, null=True)
    distmin = models.FloatField(blank=True, null=True)
    distmax = models.FloatField(blank=True, null=True)
    e_dist = models.FloatField(blank=True, null=True)
    distinput = models.FloatField(blank=True, null=True)
    e_distinput = models.FloatField(blank=True, null=True)
    disttmean = models.FloatField(blank=True, null=True)
    r_distinput = models.FloatField(blank=True, null=True)
    ndist = models.FloatField(blank=True, null=True)
    r1 = models.FloatField(blank=True, null=True)
    r2 = models.FloatField(blank=True, null=True)
    pa = models.FloatField(blank=True, null=True)
    r_r1 = models.FloatField(blank=True, null=True)
    idcat = models.FloatField(blank=True, null=True)
    gaia_uppercase_g_mag = models.FloatField(blank=True, null=True)
    bpmag = models.FloatField(blank=True, null=True)
    pm = models.FloatField(blank=True, null=True)
    angdist = models.FloatField(blank=True, null=True)
    rmagpsf = models.FloatField(blank=True, null=True)
    gmag = models.FloatField(blank=True, null=True)
    rmag = models.FloatField(blank=True, null=True)
    imag = models.FloatField(blank=True, null=True)
    zmag = models.FloatField(blank=True, null=True)
    w1mag = models.FloatField(blank=True, null=True)
    w2mag = models.FloatField(blank=True, null=True)
    dk = models.FloatField(blank=True, null=True)
    r_gmag = models.FloatField(blank=True, null=True)
    r_w1mag = models.FloatField(blank=True, null=True)
    ebv = models.FloatField(blank=True, null=True)
    logm = models.FloatField(blank=True, null=True)
    frel = models.FloatField(blank=True, null=True)
    fracnearby = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "cosmicflows4_q3c"


class DesiSpecQ3C(models.Model):
    did = models.AutoField(primary_key=True)
    targetid = models.BigIntegerField(blank=True, null=True)
    survey = models.CharField(max_length=7, blank=True, null=True)
    program = models.CharField(max_length=6, blank=True, null=True)
    healpix = models.IntegerField(blank=True, null=True)
    spgrpval = models.IntegerField(blank=True, null=True)
    z = models.FloatField(blank=True, null=True)
    zerr = models.FloatField(blank=True, null=True)
    zwarn = models.BigIntegerField(blank=True, null=True)
    chi2 = models.FloatField(blank=True, null=True)
    coeff_0 = models.FloatField(blank=True, null=True)
    coeff_1 = models.FloatField(blank=True, null=True)
    coeff_2 = models.FloatField(blank=True, null=True)
    coeff_3 = models.FloatField(blank=True, null=True)
    coeff_4 = models.FloatField(blank=True, null=True)
    coeff_5 = models.FloatField(blank=True, null=True)
    coeff_6 = models.FloatField(blank=True, null=True)
    coeff_7 = models.FloatField(blank=True, null=True)
    coeff_8 = models.FloatField(blank=True, null=True)
    coeff_9 = models.FloatField(blank=True, null=True)
    npixels = models.BigIntegerField(blank=True, null=True)
    spectype = models.CharField(max_length=6, blank=True, null=True)
    subtype = models.CharField(max_length=20, blank=True, null=True)
    ncoeff = models.BigIntegerField(blank=True, null=True)
    deltachi2 = models.FloatField(blank=True, null=True)
    coadd_fiberstatus = models.IntegerField(blank=True, null=True)
    target_ra = models.FloatField(blank=True, null=True)
    target_dec = models.FloatField(blank=True, null=True)
    pmra = models.FloatField(blank=True, null=True)
    pmdec = models.FloatField(blank=True, null=True)
    ref_epoch = models.FloatField(blank=True, null=True)
    fa_target = models.BigIntegerField(blank=True, null=True)
    fa_type = models.IntegerField(blank=True, null=True)
    objtype = models.CharField(max_length=3, blank=True, null=True)
    subpriority = models.FloatField(blank=True, null=True)
    obsconditions = models.IntegerField(blank=True, null=True)
    release = models.IntegerField(blank=True, null=True)
    brickname = models.CharField(max_length=8, blank=True, null=True)
    brickid = models.IntegerField(blank=True, null=True)
    brick_objid = models.IntegerField(blank=True, null=True)
    morphtype = models.CharField(max_length=4, blank=True, null=True)
    ebv = models.FloatField(blank=True, null=True)
    flux_g = models.FloatField(blank=True, null=True)
    flux_r = models.FloatField(blank=True, null=True)
    flux_z = models.FloatField(blank=True, null=True)
    flux_w1 = models.FloatField(blank=True, null=True)
    flux_w2 = models.FloatField(blank=True, null=True)
    flux_ivar_g = models.FloatField(blank=True, null=True)
    flux_ivar_r = models.FloatField(blank=True, null=True)
    flux_ivar_z = models.FloatField(blank=True, null=True)
    flux_ivar_w1 = models.FloatField(blank=True, null=True)
    flux_ivar_w2 = models.FloatField(blank=True, null=True)
    fiberflux_g = models.FloatField(blank=True, null=True)
    fiberflux_r = models.FloatField(blank=True, null=True)
    fiberflux_z = models.FloatField(blank=True, null=True)
    fibertotflux_g = models.FloatField(blank=True, null=True)
    fibertotflux_r = models.FloatField(blank=True, null=True)
    fibertotflux_z = models.FloatField(blank=True, null=True)
    maskbits = models.IntegerField(blank=True, null=True)
    sersic = models.FloatField(blank=True, null=True)
    shape_r = models.FloatField(blank=True, null=True)
    shape_e1 = models.FloatField(blank=True, null=True)
    shape_e2 = models.FloatField(blank=True, null=True)
    ref_id = models.BigIntegerField(blank=True, null=True)
    ref_cat = models.CharField(max_length=2, blank=True, null=True)
    gaia_phot_g_mean_mag = models.FloatField(blank=True, null=True)
    gaia_phot_bp_mean_mag = models.FloatField(blank=True, null=True)
    gaia_phot_rp_mean_mag = models.FloatField(blank=True, null=True)
    parallax = models.FloatField(blank=True, null=True)
    photsys = models.CharField(max_length=1, blank=True, null=True)
    priority_init = models.BigIntegerField(blank=True, null=True)
    numobs_init = models.BigIntegerField(blank=True, null=True)
    cmx_target = models.BigIntegerField(blank=True, null=True)
    sv1_desi_target = models.BigIntegerField(blank=True, null=True)
    sv1_bgs_target = models.BigIntegerField(blank=True, null=True)
    sv1_mws_target = models.BigIntegerField(blank=True, null=True)
    sv1_scnd_target = models.BigIntegerField(blank=True, null=True)
    sv2_desi_target = models.BigIntegerField(blank=True, null=True)
    sv2_bgs_target = models.BigIntegerField(blank=True, null=True)
    sv2_mws_target = models.BigIntegerField(blank=True, null=True)
    sv2_scnd_target = models.BigIntegerField(blank=True, null=True)
    sv3_desi_target = models.BigIntegerField(blank=True, null=True)
    sv3_bgs_target = models.BigIntegerField(blank=True, null=True)
    sv3_mws_target = models.BigIntegerField(blank=True, null=True)
    sv3_scnd_target = models.BigIntegerField(blank=True, null=True)
    desi_target = models.BigIntegerField(blank=True, null=True)
    bgs_target = models.BigIntegerField(blank=True, null=True)
    mws_target = models.BigIntegerField(blank=True, null=True)
    scnd_target = models.BigIntegerField(blank=True, null=True)
    plate_ra = models.FloatField(blank=True, null=True)
    plate_dec = models.FloatField(blank=True, null=True)
    coadd_numexp = models.IntegerField(blank=True, null=True)
    coadd_exptime = models.FloatField(blank=True, null=True)
    coadd_numnight = models.IntegerField(blank=True, null=True)
    coadd_numtile = models.IntegerField(blank=True, null=True)
    mean_delta_x = models.FloatField(blank=True, null=True)
    rms_delta_x = models.FloatField(blank=True, null=True)
    mean_delta_y = models.FloatField(blank=True, null=True)
    rms_delta_y = models.FloatField(blank=True, null=True)
    mean_fiber_ra = models.FloatField(blank=True, null=True)
    std_fiber_ra = models.FloatField(blank=True, null=True)
    mean_fiber_dec = models.FloatField(blank=True, null=True)
    std_fiber_dec = models.FloatField(blank=True, null=True)
    mean_psf_to_fiber_specflux = models.FloatField(blank=True, null=True)
    tsnr2_gpbdark_b = models.FloatField(blank=True, null=True)
    tsnr2_elg_b = models.FloatField(blank=True, null=True)
    tsnr2_gpbbright_b = models.FloatField(blank=True, null=True)
    tsnr2_lya_b = models.FloatField(blank=True, null=True)
    tsnr2_bgs_b = models.FloatField(blank=True, null=True)
    tsnr2_gpbbackup_b = models.FloatField(blank=True, null=True)
    tsnr2_qso_b = models.FloatField(blank=True, null=True)
    tsnr2_lrg_b = models.FloatField(blank=True, null=True)
    tsnr2_gpbdark_r = models.FloatField(blank=True, null=True)
    tsnr2_elg_r = models.FloatField(blank=True, null=True)
    tsnr2_gpbbright_r = models.FloatField(blank=True, null=True)
    tsnr2_lya_r = models.FloatField(blank=True, null=True)
    tsnr2_bgs_r = models.FloatField(blank=True, null=True)
    tsnr2_gpbbackup_r = models.FloatField(blank=True, null=True)
    tsnr2_qso_r = models.FloatField(blank=True, null=True)
    tsnr2_lrg_r = models.FloatField(blank=True, null=True)
    tsnr2_gpbdark_z = models.FloatField(blank=True, null=True)
    tsnr2_elg_z = models.FloatField(blank=True, null=True)
    tsnr2_gpbbright_z = models.FloatField(blank=True, null=True)
    tsnr2_lya_z = models.FloatField(blank=True, null=True)
    tsnr2_bgs_z = models.FloatField(blank=True, null=True)
    tsnr2_gpbbackup_z = models.FloatField(blank=True, null=True)
    tsnr2_qso_z = models.FloatField(blank=True, null=True)
    tsnr2_lrg_z = models.FloatField(blank=True, null=True)
    tsnr2_gpbdark = models.FloatField(blank=True, null=True)
    tsnr2_elg = models.FloatField(blank=True, null=True)
    tsnr2_gpbbright = models.FloatField(blank=True, null=True)
    tsnr2_lya = models.FloatField(blank=True, null=True)
    tsnr2_bgs = models.FloatField(blank=True, null=True)
    tsnr2_gpbbackup = models.FloatField(blank=True, null=True)
    tsnr2_qso = models.FloatField(blank=True, null=True)
    tsnr2_lrg = models.FloatField(blank=True, null=True)
    sv_nspec = models.IntegerField(blank=True, null=True)
    sv_primary = models.BooleanField(blank=True, null=True)
    zcat_nspec = models.IntegerField(blank=True, null=True)
    zcat_primary = models.BooleanField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "desi_spec_q3c"


class DesiDr1Q3C(models.Model):
    targetid = models.BigIntegerField(blank=True, null=True)
    survey = models.TextField(blank=True, null=True)
    program = models.TextField(blank=True, null=True)
    healpix = models.IntegerField(blank=True, null=True)
    spgrpval = models.IntegerField(blank=True, null=True)
    z = models.FloatField(blank=True, null=True)
    zerr = models.FloatField(blank=True, null=True)
    zwarn = models.BigIntegerField(blank=True, null=True)
    chi2 = models.FloatField(blank=True, null=True)
    coeff_00 = models.FloatField(blank=True, null=True)
    coeff_01 = models.FloatField(blank=True, null=True)
    coeff_02 = models.FloatField(blank=True, null=True)
    coeff_03 = models.FloatField(blank=True, null=True)
    coeff_04 = models.FloatField(blank=True, null=True)
    coeff_05 = models.FloatField(blank=True, null=True)
    coeff_06 = models.FloatField(blank=True, null=True)
    coeff_07 = models.FloatField(blank=True, null=True)
    coeff_08 = models.FloatField(blank=True, null=True)
    coeff_09 = models.FloatField(blank=True, null=True)
    npixels = models.BigIntegerField(blank=True, null=True)
    spectype = models.TextField(blank=True, null=True)
    subtype = models.TextField(blank=True, null=True)
    ncoeff = models.BigIntegerField(blank=True, null=True)
    deltachi2 = models.FloatField(blank=True, null=True)
    coadd_fiberstatus = models.IntegerField(blank=True, null=True)
    target_ra = models.FloatField(blank=True, null=True)
    target_dec = models.FloatField(blank=True, null=True)
    pmra = models.FloatField(blank=True, null=True)
    pmdec = models.FloatField(blank=True, null=True)
    ref_epoch = models.FloatField(blank=True, null=True)
    fa_target = models.BigIntegerField(blank=True, null=True)
    fa_type = models.SmallIntegerField(blank=True, null=True)
    objtype = models.TextField(blank=True, null=True)
    subpriority = models.FloatField(blank=True, null=True)
    obsconditions = models.IntegerField(blank=True, null=True)
    release = models.SmallIntegerField(blank=True, null=True)
    brickname = models.TextField(blank=True, null=True)
    brickid = models.IntegerField(blank=True, null=True)
    brick_objid = models.IntegerField(blank=True, null=True)
    morphtype = models.TextField(blank=True, null=True)
    ebv = models.FloatField(blank=True, null=True)
    flux_g = models.FloatField(blank=True, null=True)
    flux_r = models.FloatField(blank=True, null=True)
    flux_z = models.FloatField(blank=True, null=True)
    flux_w1 = models.FloatField(blank=True, null=True)
    flux_w2 = models.FloatField(blank=True, null=True)
    flux_ivar_g = models.FloatField(blank=True, null=True)
    flux_ivar_r = models.FloatField(blank=True, null=True)
    flux_ivar_z = models.FloatField(blank=True, null=True)
    flux_ivar_w1 = models.FloatField(blank=True, null=True)
    flux_ivar_w2 = models.FloatField(blank=True, null=True)
    fiberflux_g = models.FloatField(blank=True, null=True)
    fiberflux_r = models.FloatField(blank=True, null=True)
    fiberflux_z = models.FloatField(blank=True, null=True)
    fibertotflux_g = models.FloatField(blank=True, null=True)
    fibertotflux_r = models.FloatField(blank=True, null=True)
    fibertotflux_z = models.FloatField(blank=True, null=True)
    maskbits = models.SmallIntegerField(blank=True, null=True)
    sersic = models.FloatField(blank=True, null=True)
    shape_r = models.FloatField(blank=True, null=True)
    shape_e1 = models.FloatField(blank=True, null=True)
    shape_e2 = models.FloatField(blank=True, null=True)
    ref_id = models.BigIntegerField(blank=True, null=True)
    ref_cat = models.TextField(blank=True, null=True)
    gaia_phot_g_mean_mag = models.FloatField(blank=True, null=True)
    gaia_phot_bp_mean_mag = models.FloatField(blank=True, null=True)
    gaia_phot_rp_mean_mag = models.FloatField(blank=True, null=True)
    parallax = models.FloatField(blank=True, null=True)
    photsys = models.TextField(blank=True, null=True)
    priority_init = models.BigIntegerField(blank=True, null=True)
    numobs_init = models.BigIntegerField(blank=True, null=True)
    cmx_target = models.BigIntegerField(blank=True, null=True)
    desi_target = models.BigIntegerField(blank=True, null=True)
    bgs_target = models.BigIntegerField(blank=True, null=True)
    mws_target = models.BigIntegerField(blank=True, null=True)
    scnd_target = models.BigIntegerField(blank=True, null=True)
    sv1_desi_target = models.BigIntegerField(blank=True, null=True)
    sv1_bgs_target = models.BigIntegerField(blank=True, null=True)
    sv1_mws_target = models.BigIntegerField(blank=True, null=True)
    sv1_scnd_target = models.BigIntegerField(blank=True, null=True)
    sv2_desi_target = models.BigIntegerField(blank=True, null=True)
    sv2_bgs_target = models.BigIntegerField(blank=True, null=True)
    sv2_mws_target = models.BigIntegerField(blank=True, null=True)
    sv2_scnd_target = models.BigIntegerField(blank=True, null=True)
    sv3_desi_target = models.BigIntegerField(blank=True, null=True)
    sv3_bgs_target = models.BigIntegerField(blank=True, null=True)
    sv3_mws_target = models.BigIntegerField(blank=True, null=True)
    sv3_scnd_target = models.BigIntegerField(blank=True, null=True)
    plate_ra = models.FloatField(blank=True, null=True)
    plate_dec = models.FloatField(blank=True, null=True)
    coadd_numexp = models.SmallIntegerField(blank=True, null=True)
    coadd_exptime = models.FloatField(blank=True, null=True)
    coadd_numnight = models.SmallIntegerField(blank=True, null=True)
    coadd_numtile = models.SmallIntegerField(blank=True, null=True)
    mean_delta_x = models.FloatField(blank=True, null=True)
    rms_delta_x = models.FloatField(blank=True, null=True)
    mean_delta_y = models.FloatField(blank=True, null=True)
    rms_delta_y = models.FloatField(blank=True, null=True)
    mean_psf_to_fiber_specflux = models.FloatField(blank=True, null=True)
    mean_fiber_ra = models.FloatField(blank=True, null=True)
    std_fiber_ra = models.FloatField(blank=True, null=True)
    mean_fiber_dec = models.FloatField(blank=True, null=True)
    std_fiber_dec = models.FloatField(blank=True, null=True)
    min_mjd = models.FloatField(blank=True, null=True)
    max_mjd = models.FloatField(blank=True, null=True)
    mean_mjd = models.FloatField(blank=True, null=True)
    tsnr2_gpbdark_b = models.FloatField(blank=True, null=True)
    tsnr2_elg_b = models.FloatField(blank=True, null=True)
    tsnr2_gpbbright_b = models.FloatField(blank=True, null=True)
    tsnr2_lya_b = models.FloatField(blank=True, null=True)
    tsnr2_bgs_b = models.FloatField(blank=True, null=True)
    tsnr2_gpbbackup_b = models.FloatField(blank=True, null=True)
    tsnr2_qso_b = models.FloatField(blank=True, null=True)
    tsnr2_lrg_b = models.FloatField(blank=True, null=True)
    tsnr2_gpbdark_r = models.FloatField(blank=True, null=True)
    tsnr2_elg_r = models.FloatField(blank=True, null=True)
    tsnr2_gpbbright_r = models.FloatField(blank=True, null=True)
    tsnr2_lya_r = models.FloatField(blank=True, null=True)
    tsnr2_bgs_r = models.FloatField(blank=True, null=True)
    tsnr2_gpbbackup_r = models.FloatField(blank=True, null=True)
    tsnr2_qso_r = models.FloatField(blank=True, null=True)
    tsnr2_lrg_r = models.FloatField(blank=True, null=True)
    tsnr2_gpbdark_z = models.FloatField(blank=True, null=True)
    tsnr2_elg_z = models.FloatField(blank=True, null=True)
    tsnr2_gpbbright_z = models.FloatField(blank=True, null=True)
    tsnr2_lya_z = models.FloatField(blank=True, null=True)
    tsnr2_bgs_z = models.FloatField(blank=True, null=True)
    tsnr2_gpbbackup_z = models.FloatField(blank=True, null=True)
    tsnr2_qso_z = models.FloatField(blank=True, null=True)
    tsnr2_lrg_z = models.FloatField(blank=True, null=True)
    tsnr2_gpbdark = models.FloatField(blank=True, null=True)
    tsnr2_elg = models.FloatField(blank=True, null=True)
    tsnr2_gpbbright = models.FloatField(blank=True, null=True)
    tsnr2_lya = models.FloatField(blank=True, null=True)
    tsnr2_bgs = models.FloatField(blank=True, null=True)
    tsnr2_gpbbackup = models.FloatField(blank=True, null=True)
    tsnr2_qso = models.FloatField(blank=True, null=True)
    tsnr2_lrg = models.FloatField(blank=True, null=True)
    main_nspec = models.SmallIntegerField(blank=True, null=True)
    main_primary = models.BooleanField(blank=True, null=True)
    sv_nspec = models.SmallIntegerField(blank=True, null=True)
    sv_primary = models.BooleanField(blank=True, null=True)
    zcat_nspec = models.SmallIntegerField(blank=True, null=True)
    zcat_primary = models.BooleanField(blank=True, null=True)
    desiname = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "desi_dr1_q3c"


class FermiLatQ3C(models.Model):
    fid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=24)
    b = models.FloatField(blank=True, null=True)
    l = models.FloatField(blank=True, null=True)
    lbllac = models.FloatField(blank=True, null=True)
    pbllac = models.FloatField(blank=True, null=True)
    pfsrq = models.FloatField(blank=True, null=True)
    classification = models.CharField(max_length=16, blank=True, null=True)
    lbllaclit = models.FloatField(blank=True, null=True)
    classlit = models.CharField(max_length=16, blank=True, null=True)
    simbad = models.CharField(max_length=8, blank=True, null=True)
    ra = models.FloatField(blank=True, null=True)
    dec = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "fermi_lat_q3c"


class Gaiadr3VariableQ3C(models.Model):
    gid = models.AutoField(primary_key=True)
    ra = models.FloatField(blank=True, null=True)
    ra_error = models.FloatField(blank=True, null=True)
    dec = models.FloatField(blank=True, null=True)
    dec_error = models.FloatField(blank=True, null=True)
    pmra = models.FloatField(blank=True, null=True)
    pmra_error = models.FloatField(blank=True, null=True)
    pmdec = models.FloatField(blank=True, null=True)
    pmdec_error = models.FloatField(blank=True, null=True)
    parallax = models.FloatField(blank=True, null=True)
    parallax_error = models.FloatField(blank=True, null=True)
    solution_id = models.BigIntegerField(blank=True, null=True)
    source_id = models.BigIntegerField(blank=True, null=True)
    classification = models.CharField(max_length=16, blank=True, null=True)
    best_class_name = models.CharField(max_length=26, blank=True, null=True)
    best_class_score = models.FloatField(blank=True, null=True)
    num_selected_g_fov = models.IntegerField(blank=True, null=True)
    mean_obs_time_g_fov = models.FloatField(blank=True, null=True)
    time_duration_g_fov = models.FloatField(blank=True, null=True)
    min_mag_g_fov = models.FloatField(blank=True, null=True)
    max_mag_g_fov = models.FloatField(blank=True, null=True)
    mean_mag_g_fov = models.FloatField(blank=True, null=True)
    median_mag_g_fov = models.FloatField(blank=True, null=True)
    range_mag_g_fov = models.FloatField(blank=True, null=True)
    trimmed_range_mag_g_fov = models.FloatField(blank=True, null=True)
    std_dev_mag_g_fov = models.FloatField(blank=True, null=True)
    skewness_mag_g_fov = models.FloatField(blank=True, null=True)
    kurtosis_mag_g_fov = models.FloatField(blank=True, null=True)
    mad_mag_g_fov = models.FloatField(blank=True, null=True)
    abbe_mag_g_fov = models.FloatField(blank=True, null=True)
    iqr_mag_g_fov = models.FloatField(blank=True, null=True)
    stetson_mag_g_fov = models.FloatField(blank=True, null=True)
    std_dev_over_rms_err_mag_g_fov = models.FloatField(blank=True, null=True)
    outlier_median_g_fov = models.FloatField(blank=True, null=True)
    num_selected_bp = models.IntegerField(blank=True, null=True)
    mean_obs_time_bp = models.FloatField(blank=True, null=True)
    time_duration_bp = models.FloatField(blank=True, null=True)
    min_mag_bp = models.FloatField(blank=True, null=True)
    max_mag_bp = models.FloatField(blank=True, null=True)
    mean_mag_bp = models.FloatField(blank=True, null=True)
    median_mag_bp = models.FloatField(blank=True, null=True)
    range_mag_bp = models.FloatField(blank=True, null=True)
    trimmed_range_mag_bp = models.FloatField(blank=True, null=True)
    std_dev_mag_bp = models.FloatField(blank=True, null=True)
    skewness_mag_bp = models.FloatField(blank=True, null=True)
    kurtosis_mag_bp = models.FloatField(blank=True, null=True)
    mad_mag_bp = models.FloatField(blank=True, null=True)
    abbe_mag_bp = models.FloatField(blank=True, null=True)
    iqr_mag_bp = models.FloatField(blank=True, null=True)
    stetson_mag_bp = models.FloatField(blank=True, null=True)
    std_dev_over_rms_err_mag_bp = models.FloatField(blank=True, null=True)
    outlier_median_bp = models.FloatField(blank=True, null=True)
    num_selected_rp = models.IntegerField(blank=True, null=True)
    mean_obs_time_rp = models.FloatField(blank=True, null=True)
    time_duration_rp = models.FloatField(blank=True, null=True)
    min_mag_rp = models.FloatField(blank=True, null=True)
    max_mag_rp = models.FloatField(blank=True, null=True)
    mean_mag_rp = models.FloatField(blank=True, null=True)
    median_mag_rp = models.FloatField(blank=True, null=True)
    range_mag_rp = models.FloatField(blank=True, null=True)
    trimmed_range_mag_rp = models.FloatField(blank=True, null=True)
    std_dev_mag_rp = models.FloatField(blank=True, null=True)
    skewness_mag_rp = models.FloatField(blank=True, null=True)
    kurtosis_mag_rp = models.FloatField(blank=True, null=True)
    mad_mag_rp = models.FloatField(blank=True, null=True)
    abbe_mag_rp = models.FloatField(blank=True, null=True)
    iqr_mag_rp = models.FloatField(blank=True, null=True)
    stetson_mag_rp = models.FloatField(blank=True, null=True)
    std_dev_over_rms_err_mag_rp = models.FloatField(blank=True, null=True)
    outlier_median_rp = models.FloatField(blank=True, null=True)
    in_vari_classification_result = models.BooleanField(blank=True, null=True)
    in_vari_rrlyrae = models.BooleanField(blank=True, null=True)
    in_vari_cepheid = models.BooleanField(blank=True, null=True)
    in_vari_planetary_transit = models.BooleanField(blank=True, null=True)
    in_vari_short_timescale = models.BooleanField(blank=True, null=True)
    in_vari_long_period_variable = models.BooleanField(blank=True, null=True)
    in_vari_eclipsing_binary = models.BooleanField(blank=True, null=True)
    in_vari_rotation_modulation = models.BooleanField(blank=True, null=True)
    in_vari_ms_oscillator = models.BooleanField(blank=True, null=True)
    in_vari_agn = models.BooleanField(blank=True, null=True)
    in_vari_microlensing = models.BooleanField(blank=True, null=True)
    in_vari_compact_companion = models.BooleanField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "gaiadr3variable_q3c"


class GladePlusQ3C(models.Model):
    gid = models.AutoField(primary_key=True)
    gn = models.IntegerField(blank=True, null=True)
    pgc = models.IntegerField(blank=True, null=True)
    gwgc = models.CharField(max_length=64, blank=True, null=True)
    hyperleda = models.CharField(max_length=64, blank=True, null=True)
    twomass = models.CharField(max_length=64, blank=True, null=True)
    wise = models.CharField(max_length=64, blank=True, null=True)
    sdss = models.CharField(max_length=64, blank=True, null=True)
    o_flag = models.CharField(max_length=1, blank=True, null=True)
    ra = models.FloatField(blank=True, null=True)
    dec = models.FloatField(blank=True, null=True)
    b = models.FloatField(blank=True, null=True)
    b_err = models.FloatField(blank=True, null=True)
    b_flag = models.IntegerField(blank=True, null=True)
    b_abs = models.FloatField(blank=True, null=True)
    j = models.FloatField(blank=True, null=True)
    j_err = models.FloatField(blank=True, null=True)
    h = models.FloatField(blank=True, null=True)
    h_err = models.FloatField(blank=True, null=True)
    k = models.FloatField(blank=True, null=True)
    k_err = models.FloatField(blank=True, null=True)
    w1 = models.FloatField(blank=True, null=True)
    w1_err = models.FloatField(blank=True, null=True)
    w2 = models.FloatField(blank=True, null=True)
    w2_err = models.FloatField(blank=True, null=True)
    w1_flag = models.IntegerField(blank=True, null=True)
    b_j = models.FloatField(blank=True, null=True)
    b_j_err = models.FloatField(blank=True, null=True)
    z_helio = models.FloatField(blank=True, null=True)
    z_cmb = models.FloatField(blank=True, null=True)
    z_flag = models.IntegerField(blank=True, null=True)
    v_err = models.FloatField(blank=True, null=True)
    z_err = models.FloatField(blank=True, null=True)
    d_l = models.FloatField(blank=True, null=True)
    d_l_err = models.FloatField(blank=True, null=True)
    dist_flag = models.IntegerField(blank=True, null=True)
    mstar = models.FloatField(blank=True, null=True)
    mstar_err = models.FloatField(blank=True, null=True)
    mrate = models.FloatField(blank=True, null=True)
    mrate_err = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "glade_plus_q3c"


class GwgcQ3C(models.Model):
    gid = models.AutoField(primary_key=True)
    pgc = models.IntegerField(blank=True, null=True)
    name = models.CharField(max_length=128)
    rah = models.FloatField(blank=True, null=True)
    ra = models.FloatField(blank=True, null=True)
    dec = models.FloatField(blank=True, null=True)
    tt = models.FloatField(blank=True, null=True)
    b_app = models.FloatField(blank=True, null=True)
    a = models.FloatField(blank=True, null=True)
    e_a = models.FloatField(blank=True, null=True)
    b = models.FloatField(blank=True, null=True)
    e_b = models.FloatField(blank=True, null=True)
    b_div_a = models.FloatField(blank=True, null=True)
    e_b_div_a = models.FloatField(blank=True, null=True)
    pa = models.FloatField(blank=True, null=True)
    b_abs = models.FloatField(blank=True, null=True)
    dist = models.FloatField(blank=True, null=True)
    e_dist = models.FloatField(blank=True, null=True)
    e_b_app = models.FloatField(blank=True, null=True)
    e_b_abs = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "gwgc_q3c"


class Hecate1Q3C(models.Model):
    hid = models.AutoField(primary_key=True)
    pgc = models.IntegerField(blank=True, null=True)
    objname = models.CharField(max_length=64, blank=True, null=True)
    id_ned = models.CharField(max_length=64, blank=True, null=True)
    id_nedd = models.CharField(max_length=64, blank=True, null=True)
    id_iras = models.CharField(max_length=64, blank=True, null=True)
    id_2mass = models.CharField(max_length=64, blank=True, null=True)
    sdss_photid = models.CharField(max_length=64, blank=True, null=True)
    sdss_specid = models.CharField(max_length=64, blank=True, null=True)
    ra = models.FloatField(blank=True, null=True)
    dec = models.FloatField(blank=True, null=True)
    f_astrom = models.IntegerField(blank=True, null=True)
    r1 = models.FloatField(blank=True, null=True)
    r2 = models.FloatField(blank=True, null=True)
    pa = models.FloatField(blank=True, null=True)
    rsource = models.CharField(max_length=1, blank=True, null=True)
    rflag = models.IntegerField(blank=True, null=True)
    t = models.FloatField(blank=True, null=True)
    e_t = models.FloatField(blank=True, null=True)
    incl = models.FloatField(blank=True, null=True)
    v = models.FloatField(blank=True, null=True)
    e_v = models.FloatField(blank=True, null=True)
    v_vir = models.FloatField(blank=True, null=True)
    e_v_vir = models.FloatField(blank=True, null=True)
    ndist = models.IntegerField(blank=True, null=True)
    edist = models.BooleanField(blank=True, null=True)
    d = models.FloatField(blank=True, null=True)
    e_d = models.FloatField(blank=True, null=True)
    d_lo68 = models.FloatField(blank=True, null=True)
    d_hi68 = models.FloatField(blank=True, null=True)
    d_lo95 = models.FloatField(blank=True, null=True)
    d_hi95 = models.FloatField(blank=True, null=True)
    dmethod = models.CharField(max_length=2, blank=True, null=True)
    ut = models.FloatField(blank=True, null=True)
    bt = models.FloatField(blank=True, null=True)
    vt = models.FloatField(blank=True, null=True)
    it = models.FloatField(blank=True, null=True)
    e_ut = models.FloatField(blank=True, null=True)
    e_bt = models.FloatField(blank=True, null=True)
    e_vt = models.FloatField(blank=True, null=True)
    e_it = models.FloatField(blank=True, null=True)
    ag = models.FloatField(blank=True, null=True)
    ai = models.FloatField(blank=True, null=True)
    s12 = models.FloatField(blank=True, null=True)
    s25 = models.FloatField(blank=True, null=True)
    s60 = models.FloatField(blank=True, null=True)
    s100 = models.FloatField(blank=True, null=True)
    q12 = models.FloatField(blank=True, null=True)
    q25 = models.FloatField(blank=True, null=True)
    q60 = models.FloatField(blank=True, null=True)
    q100 = models.FloatField(blank=True, null=True)
    wf1 = models.FloatField(blank=True, null=True)
    wf2 = models.FloatField(blank=True, null=True)
    wf3 = models.FloatField(blank=True, null=True)
    wf4 = models.FloatField(blank=True, null=True)
    e_wf1 = models.FloatField(blank=True, null=True)
    e_wf2 = models.FloatField(blank=True, null=True)
    e_wf3 = models.FloatField(blank=True, null=True)
    e_wf4 = models.FloatField(blank=True, null=True)
    wfpoint = models.BooleanField(blank=True, null=True)
    wftreat = models.BooleanField(blank=True, null=True)
    j = models.FloatField(blank=True, null=True)
    h = models.FloatField(blank=True, null=True)
    k = models.FloatField(blank=True, null=True)
    e_j = models.FloatField(blank=True, null=True)
    e_h = models.FloatField(blank=True, null=True)
    e_k = models.FloatField(blank=True, null=True)
    flag_2mass = models.IntegerField(blank=True, null=True)
    u = models.FloatField(blank=True, null=True)
    g = models.FloatField(blank=True, null=True)
    r = models.FloatField(blank=True, null=True)
    i = models.FloatField(blank=True, null=True)
    z = models.FloatField(blank=True, null=True)
    e_u = models.FloatField(blank=True, null=True)
    e_g = models.FloatField(blank=True, null=True)
    e_r = models.FloatField(blank=True, null=True)
    e_i = models.FloatField(blank=True, null=True)
    e_z = models.FloatField(blank=True, null=True)
    logl_tir = models.FloatField(blank=True, null=True)
    logl_fir = models.FloatField(blank=True, null=True)
    logl_60u = models.FloatField(blank=True, null=True)
    logl_12u = models.FloatField(blank=True, null=True)
    logl_22u = models.FloatField(blank=True, null=True)
    logl_k = models.FloatField(blank=True, null=True)
    ml_ratio = models.FloatField(blank=True, null=True)
    logsfr_tir = models.FloatField(blank=True, null=True)
    logsfr_fir = models.FloatField(blank=True, null=True)
    logsfr_60u = models.FloatField(blank=True, null=True)
    logsfr_12u = models.FloatField(blank=True, null=True)
    logsfr_22u = models.FloatField(blank=True, null=True)
    logsfr_hec = models.FloatField(blank=True, null=True)
    sfr_hec_flag = models.CharField(max_length=2, blank=True, null=True)
    logm_hec = models.FloatField(blank=True, null=True)
    logsfr_gsw = models.FloatField(blank=True, null=True)
    logm_gsw = models.FloatField(blank=True, null=True)
    min_snr = models.FloatField(blank=True, null=True)
    metal = models.FloatField(blank=True, null=True)
    flag_metal = models.IntegerField(blank=True, null=True)
    class_sp = models.IntegerField(blank=True, null=True)
    agn_s17 = models.CharField(max_length=1, blank=True, null=True)
    agn_hec = models.CharField(max_length=1, blank=True, null=True)

    class Meta:
        managed = False
        db_table = "hecate1_q3c"


class Hecate2Q3C(models.Model):
    hid = models.AutoField(primary_key=True)
    pgc = models.IntegerField(blank=True, null=True)
    objname = models.CharField(max_length=64, blank=True, null=True)
    allwise = models.CharField(max_length=64, blank=True, null=True)
    objid = models.CharField(max_length=64, blank=True, null=True)
    specobjid = models.CharField(max_length=64, blank=True, null=True)
    ps2 = models.CharField(max_length=64, blank=True, null=True)
    radeg = models.FloatField(blank=True, null=True)
    dedeg = models.FloatField(blank=True, null=True)
    fastrom = models.IntegerField(blank=True, null=True)
    r1 = models.FloatField(blank=True, null=True)
    r2 = models.FloatField(blank=True, null=True)
    pa = models.FloatField(blank=True, null=True)
    rflag = models.CharField(max_length=64, blank=True, null=True)
    rorigin = models.CharField(max_length=64, blank=True, null=True)
    t = models.FloatField(blank=True, null=True)
    e_t = models.FloatField(blank=True, null=True)
    incl = models.FloatField(blank=True, null=True)
    hrv = models.FloatField(blank=True, null=True)
    e_hrv = models.FloatField(blank=True, null=True)
    vvir = models.FloatField(blank=True, null=True)
    e_vvir = models.FloatField(blank=True, null=True)
    dist = models.FloatField(blank=True, null=True)
    e_dist = models.FloatField(blank=True, null=True)
    f_dist = models.IntegerField(blank=True, null=True)
    ag = models.FloatField(blank=True, null=True)
    ai = models.FloatField(blank=True, null=True)
    umagtot = models.FloatField(blank=True, null=True)
    bmagtot = models.FloatField(blank=True, null=True)
    vmagtot = models.FloatField(blank=True, null=True)
    imagtot = models.FloatField(blank=True, null=True)
    e_umagtot = models.FloatField(blank=True, null=True)
    e_bmagtot = models.FloatField(blank=True, null=True)
    e_vmagtot = models.FloatField(blank=True, null=True)
    e_imagtot = models.FloatField(blank=True, null=True)
    fs12 = models.FloatField(blank=True, null=True)
    fs25 = models.FloatField(blank=True, null=True)
    fs60 = models.FloatField(blank=True, null=True)
    fs100 = models.FloatField(blank=True, null=True)
    q_fs12 = models.IntegerField(blank=True, null=True)
    q_fs25 = models.IntegerField(blank=True, null=True)
    q_fs60 = models.IntegerField(blank=True, null=True)
    q_fs100 = models.IntegerField(blank=True, null=True)
    w1mag = models.FloatField(blank=True, null=True)
    w2mag = models.FloatField(blank=True, null=True)
    w3mag = models.FloatField(blank=True, null=True)
    w4mag = models.FloatField(blank=True, null=True)
    e_w1mag = models.FloatField(blank=True, null=True)
    e_w2mag = models.FloatField(blank=True, null=True)
    e_w3mag = models.FloatField(blank=True, null=True)
    e_w4mag = models.FloatField(blank=True, null=True)
    allwiseap = models.CharField(max_length=64, blank=True, null=True)
    q_allwise = models.CharField(max_length=64, blank=True, null=True)
    wf1mag = models.FloatField(blank=True, null=True)
    wf2mag = models.FloatField(blank=True, null=True)
    wf3mag = models.FloatField(blank=True, null=True)
    wf4mag = models.FloatField(blank=True, null=True)
    e_wf1mag = models.FloatField(blank=True, null=True)
    e_wf2mag = models.FloatField(blank=True, null=True)
    e_wf3mag = models.FloatField(blank=True, null=True)
    e_wf4mag = models.FloatField(blank=True, null=True)
    jmag = models.FloatField(blank=True, null=True)
    hmag = models.FloatField(blank=True, null=True)
    kmag = models.FloatField(blank=True, null=True)
    e_jmag = models.FloatField(blank=True, null=True)
    e_hmag = models.FloatField(blank=True, null=True)
    e_kmag = models.FloatField(blank=True, null=True)
    r2mass = models.IntegerField(blank=True, null=True)
    umag = models.FloatField(blank=True, null=True)
    gmag = models.FloatField(blank=True, null=True)
    rmag = models.FloatField(blank=True, null=True)
    imag = models.FloatField(blank=True, null=True)
    zmag = models.FloatField(blank=True, null=True)
    ymag = models.FloatField(blank=True, null=True)
    e_umag = models.FloatField(blank=True, null=True)
    e_gmag = models.FloatField(blank=True, null=True)
    e_rmag = models.FloatField(blank=True, null=True)
    e_imag = models.FloatField(blank=True, null=True)
    e_zmag = models.FloatField(blank=True, null=True)
    e_ymag = models.FloatField(blank=True, null=True)
    roptphot = models.CharField(max_length=64, blank=True, null=True)
    q_optphot = models.CharField(max_length=64, blank=True, null=True)
    fhbeta = models.FloatField(blank=True, null=True)
    e_fhbeta = models.FloatField(blank=True, null=True)
    foiii5007 = models.FloatField(blank=True, null=True)
    e_foiii5007 = models.FloatField(blank=True, null=True)
    foi6300 = models.FloatField(blank=True, null=True)
    e_foi6300 = models.FloatField(blank=True, null=True)
    fhalpha = models.FloatField(blank=True, null=True)
    e_fhalpha = models.FloatField(blank=True, null=True)
    fnii6584 = models.FloatField(blank=True, null=True)
    e_fnii6584 = models.FloatField(blank=True, null=True)
    fsii6717 = models.FloatField(blank=True, null=True)
    e_fsii6717 = models.FloatField(blank=True, null=True)
    fsii6731 = models.FloatField(blank=True, null=True)
    e_fsii6731 = models.FloatField(blank=True, null=True)
    rspec = models.CharField(max_length=64, blank=True, null=True)
    w1_w2_rf = models.FloatField(blank=True, null=True)
    w2_w3_rf = models.FloatField(blank=True, null=True)
    g_r_fib_rf = models.FloatField(blank=True, null=True)
    activclass = models.IntegerField(blank=True, null=True)
    ractivclass = models.CharField(max_length=64, blank=True, null=True)
    sfgprob = models.FloatField(blank=True, null=True)
    agnprob = models.FloatField(blank=True, null=True)
    linerprob = models.FloatField(blank=True, null=True)
    compprob = models.FloatField(blank=True, null=True)
    passprob = models.FloatField(blank=True, null=True)
    ebv = models.FloatField(blank=True, null=True)
    e_ebv = models.FloatField(blank=True, null=True)
    logsfrgsw = models.FloatField(blank=True, null=True)
    logmstargsw = models.FloatField(blank=True, null=True)
    logsfrhec = models.FloatField(blank=True, null=True)
    q_logsfrhec = models.CharField(max_length=64, blank=True, null=True)
    r_logsfrhec = models.CharField(max_length=64, blank=True, null=True)
    n_logsfrhec = models.CharField(max_length=64, blank=True, null=True)
    logmstarhec = models.FloatField(blank=True, null=True)
    q_logmstarhec = models.CharField(max_length=64, blank=True, null=True)
    r_logmstarhec = models.CharField(max_length=64, blank=True, null=True)
    n_logmstarhec = models.CharField(max_length=64, blank=True, null=True)
    metal = models.FloatField(blank=True, null=True)
    n_metal = models.CharField(max_length=64, blank=True, null=True)
    logmbh = models.FloatField(blank=True, null=True)
    r_logmbh = models.CharField(max_length=64, blank=True, null=True)
    dupflag = models.IntegerField(blank=True, null=True)
    blendflag = models.CharField(max_length=64, blank=True, null=True)
    star = models.CharField(max_length=64, blank=True, null=True)
    wcnotes = models.CharField(max_length=64, blank=True, null=True)
    notes = models.CharField(max_length=64, blank=True, null=True)

    class Meta:
        managed = False
        db_table = "hecate2_q3c"


class LsDr9NorthQ3C(models.Model):
    lid = models.BigAutoField(primary_key=True)
    release = models.SmallIntegerField(blank=True, null=True)
    brickname = models.CharField(max_length=64, blank=True, null=True)
    objid = models.IntegerField(blank=True, null=True)
    type = models.CharField(max_length=64, blank=True, null=True)
    ra = models.FloatField(blank=True, null=True)
    dec = models.FloatField(blank=True, null=True)
    ra_ivar = models.FloatField(blank=True, null=True)
    dec_ivar = models.FloatField(blank=True, null=True)
    dchisq = models.FloatField(blank=True, null=True)
    ebv = models.FloatField(blank=True, null=True)
    flux_g = models.FloatField(blank=True, null=True)
    flux_r = models.FloatField(blank=True, null=True)
    flux_z = models.FloatField(blank=True, null=True)
    flux_w1 = models.FloatField(blank=True, null=True)
    flux_w2 = models.FloatField(blank=True, null=True)
    flux_w3 = models.FloatField(blank=True, null=True)
    flux_w4 = models.FloatField(blank=True, null=True)
    flux_ivar_g = models.FloatField(blank=True, null=True)
    flux_ivar_r = models.FloatField(blank=True, null=True)
    flux_ivar_z = models.FloatField(blank=True, null=True)
    flux_ivar_w1 = models.FloatField(blank=True, null=True)
    flux_ivar_w2 = models.FloatField(blank=True, null=True)
    flux_ivar_w3 = models.FloatField(blank=True, null=True)
    flux_ivar_w4 = models.FloatField(blank=True, null=True)
    mw_transmission_g = models.FloatField(blank=True, null=True)
    mw_transmission_r = models.FloatField(blank=True, null=True)
    mw_transmission_z = models.FloatField(blank=True, null=True)
    mw_transmission_w1 = models.FloatField(blank=True, null=True)
    mw_transmission_w2 = models.FloatField(blank=True, null=True)
    mw_transmission_w3 = models.FloatField(blank=True, null=True)
    mw_transmission_w4 = models.FloatField(blank=True, null=True)
    nobs_g = models.SmallIntegerField(blank=True, null=True)
    nobs_r = models.SmallIntegerField(blank=True, null=True)
    nobs_z = models.SmallIntegerField(blank=True, null=True)
    nobs_w1 = models.SmallIntegerField(blank=True, null=True)
    nobs_w2 = models.SmallIntegerField(blank=True, null=True)
    nobs_w3 = models.SmallIntegerField(blank=True, null=True)
    nobs_w4 = models.SmallIntegerField(blank=True, null=True)
    rchisq_g = models.FloatField(blank=True, null=True)
    rchisq_r = models.FloatField(blank=True, null=True)
    rchisq_z = models.FloatField(blank=True, null=True)
    rchisq_w1 = models.FloatField(blank=True, null=True)
    rchisq_w2 = models.FloatField(blank=True, null=True)
    rchisq_w3 = models.FloatField(blank=True, null=True)
    rchisq_w4 = models.FloatField(blank=True, null=True)
    fracflux_g = models.FloatField(blank=True, null=True)
    fracflux_r = models.FloatField(blank=True, null=True)
    fracflux_z = models.FloatField(blank=True, null=True)
    fracflux_w1 = models.FloatField(blank=True, null=True)
    fracflux_w2 = models.FloatField(blank=True, null=True)
    fracflux_w3 = models.FloatField(blank=True, null=True)
    fracflux_w4 = models.FloatField(blank=True, null=True)
    fracmasked_g = models.FloatField(blank=True, null=True)
    fracmasked_r = models.FloatField(blank=True, null=True)
    fracmasked_z = models.FloatField(blank=True, null=True)
    fracin_g = models.FloatField(blank=True, null=True)
    fracin_r = models.FloatField(blank=True, null=True)
    fracin_z = models.FloatField(blank=True, null=True)
    anymask_g = models.SmallIntegerField(blank=True, null=True)
    anymask_r = models.SmallIntegerField(blank=True, null=True)
    anymask_z = models.SmallIntegerField(blank=True, null=True)
    allmask_g = models.SmallIntegerField(blank=True, null=True)
    allmask_r = models.SmallIntegerField(blank=True, null=True)
    allmask_z = models.SmallIntegerField(blank=True, null=True)
    wisemask_w1 = models.SmallIntegerField(blank=True, null=True)
    wisemask_w2 = models.SmallIntegerField(blank=True, null=True)
    psfsize_g = models.FloatField(blank=True, null=True)
    psfsize_r = models.FloatField(blank=True, null=True)
    psfsize_z = models.FloatField(blank=True, null=True)
    psfdepth_g = models.FloatField(blank=True, null=True)
    psfdepth_r = models.FloatField(blank=True, null=True)
    psfdepth_z = models.FloatField(blank=True, null=True)
    galdepth_g = models.FloatField(blank=True, null=True)
    galdepth_r = models.FloatField(blank=True, null=True)
    galdepth_z = models.FloatField(blank=True, null=True)
    psfdepth_w1 = models.FloatField(blank=True, null=True)
    psfdepth_w2 = models.FloatField(blank=True, null=True)
    wise_coadd_id = models.TextField(blank=True, null=True)
    shape_r = models.FloatField(blank=True, null=True)
    shape_r_ivar = models.FloatField(blank=True, null=True)
    shape_e1 = models.FloatField(blank=True, null=True)
    shape_e1_ivar = models.FloatField(blank=True, null=True)
    shape_e2 = models.FloatField(blank=True, null=True)
    shape_e2_ivar = models.FloatField(blank=True, null=True)
    fiberflux_g = models.FloatField(blank=True, null=True)
    fiberflux_r = models.FloatField(blank=True, null=True)
    fiberflux_z = models.FloatField(blank=True, null=True)
    fibertotflux_g = models.FloatField(blank=True, null=True)
    fibertotflux_r = models.FloatField(blank=True, null=True)
    fibertotflux_z = models.FloatField(blank=True, null=True)
    ref_cat = models.TextField(blank=True, null=True)
    ref_id = models.BigIntegerField(blank=True, null=True)
    ref_epoch = models.FloatField(blank=True, null=True)
    gaia_phot_g_mean_mag = models.FloatField(blank=True, null=True)
    gaia_phot_g_mean_flux_over_error = models.FloatField(blank=True, null=True)
    gaia_phot_bp_mean_mag = models.FloatField(blank=True, null=True)
    gaia_phot_bp_mean_flux_over_error = models.FloatField(blank=True, null=True)
    gaia_phot_rp_mean_mag = models.FloatField(blank=True, null=True)
    gaia_phot_rp_mean_flux_over_error = models.FloatField(blank=True, null=True)
    gaia_astrometric_excess_noise = models.FloatField(blank=True, null=True)
    gaia_duplicated_source = models.BooleanField(blank=True, null=True)
    gaia_phot_bp_rp_excess_factor = models.FloatField(blank=True, null=True)
    gaia_astrometric_sigma5d_max = models.FloatField(blank=True, null=True)
    gaia_astrometric_params_solved = models.SmallIntegerField(blank=True, null=True)
    parallax = models.FloatField(blank=True, null=True)
    parallax_ivar = models.FloatField(blank=True, null=True)
    pmra = models.FloatField(blank=True, null=True)
    pmra_ivar = models.FloatField(blank=True, null=True)
    pmdec = models.FloatField(blank=True, null=True)
    pmdec_ivar = models.FloatField(blank=True, null=True)
    maskbits = models.SmallIntegerField(blank=True, null=True)
    fitbits = models.SmallIntegerField(blank=True, null=True)
    sersic = models.FloatField(blank=True, null=True)
    sersic_ivar = models.FloatField(blank=True, null=True)
    z_phot_mean = models.FloatField(blank=True, null=True)
    z_phot_median = models.FloatField(blank=True, null=True)
    z_phot_std = models.FloatField(blank=True, null=True)
    z_phot_l68 = models.FloatField(blank=True, null=True)
    z_phot_u68 = models.FloatField(blank=True, null=True)
    z_phot_l95 = models.FloatField(blank=True, null=True)
    z_phot_u95 = models.FloatField(blank=True, null=True)
    z_spec = models.FloatField(blank=True, null=True)
    survey = models.TextField(blank=True, null=True)
    training = models.BooleanField(blank=True, null=True)
    kfold = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "ls_dr9north_q3c"


class LsDr10SouthQ3C(models.Model):
    lid = models.BigAutoField(primary_key=True)
    brickid = models.IntegerField(blank=True, null=True)
    objid = models.IntegerField(blank=True, null=True)
    z_phot_mean = models.FloatField(blank=True, null=True)
    z_phot_median = models.FloatField(blank=True, null=True)
    z_phot_std = models.FloatField(blank=True, null=True)
    z_phot_l68 = models.FloatField(blank=True, null=True)
    z_phot_u68 = models.FloatField(blank=True, null=True)
    z_phot_l95 = models.FloatField(blank=True, null=True)
    z_phot_u95 = models.FloatField(blank=True, null=True)
    z_phot_mean_i = models.FloatField(blank=True, null=True)
    z_phot_median_i = models.FloatField(blank=True, null=True)
    z_phot_std_i = models.FloatField(blank=True, null=True)
    z_phot_l68_i = models.FloatField(blank=True, null=True)
    z_phot_u68_i = models.FloatField(blank=True, null=True)
    z_phot_l95_i = models.FloatField(blank=True, null=True)
    z_phot_u95_i = models.FloatField(blank=True, null=True)
    z_spec = models.FloatField(blank=True, null=True)
    release = models.SmallIntegerField(blank=True, null=True)
    training = models.BooleanField(blank=True, null=True)
    training_i = models.BooleanField(blank=True, null=True)
    survey = models.TextField(blank=True, null=True)
    kfold = models.IntegerField(blank=True, null=True)
    kfold_i = models.IntegerField(blank=True, null=True)
    ra = models.FloatField(blank=True, null=True)
    declination = models.FloatField(blank=True, null=True)
    flux_g = models.FloatField(blank=True, null=True)
    flux_r = models.FloatField(blank=True, null=True)
    flux_i = models.FloatField(blank=True, null=True)
    flux_z = models.FloatField(blank=True, null=True)
    flux_ivar_g = models.FloatField(blank=True, null=True)
    flux_ivar_r = models.FloatField(blank=True, null=True)
    flux_ivar_i = models.FloatField(blank=True, null=True)
    flux_ivar_z = models.FloatField(blank=True, null=True)
    flux_w1 = models.FloatField(blank=True, null=True)
    flux_w2 = models.FloatField(blank=True, null=True)
    flux_w3 = models.FloatField(blank=True, null=True)
    flux_w4 = models.FloatField(blank=True, null=True)
    flux_ivar_w1 = models.FloatField(blank=True, null=True)
    flux_ivar_w2 = models.FloatField(blank=True, null=True)
    flux_ivar_w3 = models.FloatField(blank=True, null=True)
    flux_ivar_w4 = models.FloatField(blank=True, null=True)
    mtype = models.TextField(blank=True, null=True)
    ref_cat = models.TextField(blank=True, null=True)
    ref_id = models.BigIntegerField(blank=True, null=True)
    parallax = models.FloatField(blank=True, null=True)
    parallax_ivar = models.FloatField(blank=True, null=True)
    pmra = models.FloatField(blank=True, null=True)
    pmra_ivar = models.FloatField(blank=True, null=True)
    pmdec = models.FloatField(blank=True, null=True)
    pmdec_ivar = models.FloatField(blank=True, null=True)
    gaia_phot_variable_flag = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "ls_dr10south_q3c"


class MilliquasQ3C(models.Model):
    mid = models.AutoField(primary_key=True)
    ra = models.FloatField(blank=True, null=True)
    dec = models.FloatField(blank=True, null=True)
    name = models.CharField(max_length=32, blank=True, null=True)
    objtype = models.CharField(max_length=8, blank=True, null=True)
    rmag = models.FloatField(blank=True, null=True)
    bmag = models.FloatField(blank=True, null=True)
    comment = models.CharField(max_length=8, blank=True, null=True)
    rpsf = models.CharField(max_length=1, blank=True, null=True)
    bpsf = models.CharField(max_length=1, blank=True, null=True)
    z = models.FloatField(blank=True, null=True)
    namecit = models.CharField(max_length=8, blank=True, null=True)
    zcit = models.CharField(max_length=8, blank=True, null=True)
    qpct = models.IntegerField(blank=True, null=True)
    xname = models.CharField(max_length=32, blank=True, null=True)
    rname = models.CharField(max_length=32, blank=True, null=True)
    lobe1 = models.CharField(max_length=32, blank=True, null=True)
    lobe2 = models.CharField(max_length=32, blank=True, null=True)

    class Meta:
        managed = False
        db_table = "milliquas_q3c"


class NedlvsQ3C(models.Model):
    objname = models.TextField(blank=True, null=True)
    ra = models.FloatField(blank=True, null=True)
    dec = models.FloatField(blank=True, null=True)
    objtype = models.TextField(blank=True, null=True)
    z = models.FloatField(blank=True, null=True)
    z_unc = models.FloatField(blank=True, null=True)
    z_tech = models.TextField(blank=True, null=True)
    z_qual = models.BooleanField(blank=True, null=True)
    z_qual_flag = models.BooleanField(blank=True, null=True)
    z_refcode = models.TextField(blank=True, null=True)
    zidist = models.FloatField(blank=True, null=True)
    zidist_unc = models.FloatField(blank=True, null=True)
    zidist_method = models.TextField(blank=True, null=True)
    zidist_indicator = models.TextField(blank=True, null=True)
    zidist_refcode = models.TextField(blank=True, null=True)
    distmpc = models.FloatField(blank=True, null=True)
    distmpc_unc = models.FloatField(blank=True, null=True)
    distmpc_method = models.TextField(blank=True, null=True)
    ebv = models.FloatField(blank=True, null=True)
    a_fuv_mwext = models.FloatField(blank=True, null=True)
    a_nuv_mwext = models.FloatField(blank=True, null=True)
    a_j_mwext = models.FloatField(blank=True, null=True)
    a_h_mwext = models.FloatField(blank=True, null=True)
    a_ks_mwext = models.FloatField(blank=True, null=True)
    a_w1_mwext = models.FloatField(blank=True, null=True)
    a_w2_mwext = models.FloatField(blank=True, null=True)
    a_w3_mwext = models.FloatField(blank=True, null=True)
    a_w4_mwext = models.FloatField(blank=True, null=True)
    m_fuv = models.FloatField(blank=True, null=True)
    m_fuv_unc = models.FloatField(blank=True, null=True)
    m_nuv = models.FloatField(blank=True, null=True)
    m_nuv_unc = models.FloatField(blank=True, null=True)
    lum_fuv = models.FloatField(blank=True, null=True)
    lum_fuv_unc = models.FloatField(blank=True, null=True)
    lum_nuv = models.FloatField(blank=True, null=True)
    lum_nuv_unc = models.FloatField(blank=True, null=True)
    galexphot = models.TextField(blank=True, null=True)
    m_j = models.FloatField(blank=True, null=True)
    m_j_unc = models.FloatField(blank=True, null=True)
    m_h = models.FloatField(blank=True, null=True)
    m_h_unc = models.FloatField(blank=True, null=True)
    m_ks = models.FloatField(blank=True, null=True)
    m_ks_unc = models.FloatField(blank=True, null=True)
    lum_j = models.FloatField(blank=True, null=True)
    lum_j_unc = models.FloatField(blank=True, null=True)
    lum_h = models.FloatField(blank=True, null=True)
    lum_h_unc = models.FloatField(blank=True, null=True)
    lum_ks = models.FloatField(blank=True, null=True)
    lum_ks_unc = models.FloatField(blank=True, null=True)
    tmassphot = models.TextField(blank=True, null=True)
    m_w1 = models.FloatField(blank=True, null=True)
    m_w1_unc = models.FloatField(blank=True, null=True)
    m_w2 = models.FloatField(blank=True, null=True)
    m_w2_unc = models.FloatField(blank=True, null=True)
    m_w3 = models.FloatField(blank=True, null=True)
    m_w3_unc = models.FloatField(blank=True, null=True)
    m_w4 = models.FloatField(blank=True, null=True)
    m_w4_unc = models.FloatField(blank=True, null=True)
    lum_w1 = models.FloatField(blank=True, null=True)
    lum_w1_unc = models.FloatField(blank=True, null=True)
    lum_w2 = models.FloatField(blank=True, null=True)
    lum_w2_unc = models.FloatField(blank=True, null=True)
    lum_w3 = models.FloatField(blank=True, null=True)
    lum_w3_unc = models.FloatField(blank=True, null=True)
    lum_w4 = models.FloatField(blank=True, null=True)
    lum_w4_unc = models.FloatField(blank=True, null=True)
    wisephot = models.TextField(blank=True, null=True)
    sfr_w4 = models.FloatField(blank=True, null=True)
    sfr_w4_unc = models.FloatField(blank=True, null=True)
    sfr_hybrid = models.FloatField(blank=True, null=True)
    sfr_hybrid_unc = models.FloatField(blank=True, null=True)
    et_flag = models.BooleanField(blank=True, null=True)
    mstar = models.FloatField(blank=True, null=True)
    mstar_unc = models.FloatField(blank=True, null=True)
    mlratio = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "nedlvs_q3c"


class Ps1Q3C(models.Model):
    pid = models.BigAutoField(primary_key=True)
    objid = models.BigIntegerField(blank=True, null=True)
    psps_objid = models.BigIntegerField(blank=True, null=True)
    ra = models.FloatField()
    dec = models.FloatField()
    l = models.FloatField(blank=True, null=True)
    b = models.FloatField(blank=True, null=True)
    obj_class = models.CharField(max_length=8, blank=True, null=True)
    prob_galaxy = models.FloatField(blank=True, null=True)
    prob_star = models.FloatField(blank=True, null=True)
    prob_qso = models.FloatField(blank=True, null=True)
    extra_class = models.FloatField(blank=True, null=True)
    celld_class = models.FloatField(blank=True, null=True)
    cellid_class = models.IntegerField(blank=True, null=True)
    z_phot = models.FloatField(blank=True, null=True)
    z_err = models.FloatField(blank=True, null=True)
    z_zero = models.FloatField(blank=True, null=True)
    extra_photoz = models.IntegerField(blank=True, null=True)
    celld_photoz = models.FloatField(blank=True, null=True)
    cellid_photoz = models.IntegerField(blank=True, null=True)
    ps_score = models.FloatField(blank=True, null=True)
    objname = models.CharField(max_length=64, blank=True, null=True)
    objinfoflag = models.IntegerField(blank=True, null=True)
    qualityflag = models.IntegerField(blank=True, null=True)
    ndetections = models.IntegerField(blank=True, null=True)
    ramean = models.FloatField(blank=True, null=True)
    rameanerr = models.FloatField(blank=True, null=True)
    decmean = models.FloatField(blank=True, null=True)
    decmeanerr = models.FloatField(blank=True, null=True)
    gmeanpsfmag = models.FloatField(blank=True, null=True)
    gmeanpsfmagerr = models.FloatField(blank=True, null=True)
    rmeanpsfmag = models.FloatField(blank=True, null=True)
    rmeanpsfmagerr = models.FloatField(blank=True, null=True)
    imeanpsfmag = models.FloatField(blank=True, null=True)
    imeanpsfmagerr = models.FloatField(blank=True, null=True)
    zmeanpsfmag = models.FloatField(blank=True, null=True)
    zmeanpsfmagerr = models.FloatField(blank=True, null=True)
    ymeanpsfmag = models.FloatField(blank=True, null=True)
    ymeanpsfmagerr = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "ps1_q3c"


class RomaBzcatQ3C(models.Model):
    rid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=16)
    ra = models.FloatField(blank=True, null=True)
    dec = models.FloatField(blank=True, null=True)
    l = models.FloatField(blank=True, null=True)
    b = models.FloatField(blank=True, null=True)
    z = models.FloatField(blank=True, null=True)
    z_err = models.FloatField(blank=True, null=True)
    rmag = models.FloatField(blank=True, null=True)
    classification = models.CharField(max_length=64, blank=True, null=True)
    flux = models.FloatField(blank=True, null=True)
    flux_143 = models.FloatField(blank=True, null=True)
    flux_xray = models.FloatField(blank=True, null=True)
    flux_fermi = models.FloatField(blank=True, null=True)
    aro = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "roma_bzcat_q3c"


class Sdss12PhotozQ3C(models.Model):
    sid = models.AutoField(primary_key=True)
    ra = models.FloatField(blank=True, null=True)
    dec = models.FloatField(blank=True, null=True)
    mode = models.IntegerField(blank=True, null=True)
    q_mode = models.CharField(max_length=1, blank=True, null=True)
    classifier = models.IntegerField(blank=True, null=True)
    sdss12 = models.CharField(max_length=24, blank=True, null=True)
    m_sdss12 = models.CharField(max_length=1, blank=True, null=True)
    sdssid = models.CharField(max_length=32, blank=True, null=True)
    objid = models.CharField(max_length=24, blank=True, null=True)
    specid = models.CharField(max_length=32, blank=True, null=True)
    spobjid = models.CharField(max_length=24, blank=True, null=True)
    parentid = models.CharField(max_length=24, blank=True, null=True)
    flags = models.CharField(max_length=24, blank=True, null=True)
    status = models.IntegerField(blank=True, null=True)
    e_ra = models.FloatField(blank=True, null=True)
    e_dec = models.FloatField(blank=True, null=True)
    obsdate = models.FloatField(blank=True, null=True)
    quality = models.IntegerField(blank=True, null=True)
    umag = models.FloatField(blank=True, null=True)
    e_umag = models.FloatField(blank=True, null=True)
    gmag = models.FloatField(blank=True, null=True)
    e_gmag = models.FloatField(blank=True, null=True)
    rmag = models.FloatField(blank=True, null=True)
    e_rmag = models.FloatField(blank=True, null=True)
    imag = models.FloatField(blank=True, null=True)
    e_imag = models.FloatField(blank=True, null=True)
    zmag = models.FloatField(blank=True, null=True)
    e_zmag = models.FloatField(blank=True, null=True)
    zsp = models.FloatField(blank=True, null=True)
    e_zsp = models.FloatField(blank=True, null=True)
    f_zsp = models.IntegerField(blank=True, null=True)
    vdisp = models.FloatField(blank=True, null=True)
    e_vdisp = models.FloatField(blank=True, null=True)
    spinst = models.CharField(max_length=24, blank=True, null=True)
    sptype = models.CharField(max_length=24, blank=True, null=True)
    spclass = models.CharField(max_length=24, blank=True, null=True)
    spubclass = models.CharField(max_length=24, blank=True, null=True)
    spsignal = models.FloatField(blank=True, null=True)
    u_flags = models.CharField(max_length=24, blank=True, null=True)
    u_prob = models.IntegerField(blank=True, null=True)
    u_photo = models.IntegerField(blank=True, null=True)
    u_date = models.FloatField(blank=True, null=True)
    u_prime_mag = models.FloatField(blank=True, null=True)
    e_u_prime_mag = models.FloatField(blank=True, null=True)
    u_pmag = models.FloatField(blank=True, null=True)
    e_u_pmag = models.FloatField(blank=True, null=True)
    u_upmag = models.FloatField(blank=True, null=True)
    e_u_upmag = models.FloatField(blank=True, null=True)
    u_prad = models.FloatField(blank=True, null=True)
    e_u_prad = models.FloatField(blank=True, null=True)
    u_ora = models.FloatField(blank=True, null=True)
    u_odec = models.FloatField(blank=True, null=True)
    u_dvrad = models.FloatField(blank=True, null=True)
    u_dvell = models.FloatField(blank=True, null=True)
    u_pa = models.FloatField(blank=True, null=True)
    g_flags = models.CharField(max_length=24, blank=True, null=True)
    g_prob = models.IntegerField(blank=True, null=True)
    g_photo = models.IntegerField(blank=True, null=True)
    g_date = models.FloatField(blank=True, null=True)
    g_prime_mag = models.FloatField(blank=True, null=True)
    e_g_prime_mag = models.FloatField(blank=True, null=True)
    g_pmag = models.FloatField(blank=True, null=True)
    e_g_pmag = models.FloatField(blank=True, null=True)
    g_upmag = models.FloatField(blank=True, null=True)
    e_g_upmag = models.FloatField(blank=True, null=True)
    g_prad = models.FloatField(blank=True, null=True)
    e_g_prad = models.FloatField(blank=True, null=True)
    g_ora = models.FloatField(blank=True, null=True)
    g_odec = models.FloatField(blank=True, null=True)
    g_dvrad = models.FloatField(blank=True, null=True)
    g_dvell = models.FloatField(blank=True, null=True)
    g_pa = models.FloatField(blank=True, null=True)
    r_flags = models.CharField(max_length=24, blank=True, null=True)
    r_prob = models.IntegerField(blank=True, null=True)
    r_photo = models.IntegerField(blank=True, null=True)
    r_date = models.FloatField(blank=True, null=True)
    r_prime_mag = models.FloatField(blank=True, null=True)
    e_r_prime_mag = models.FloatField(blank=True, null=True)
    r_pmag = models.FloatField(blank=True, null=True)
    e_r_pmag = models.FloatField(blank=True, null=True)
    r_upmag = models.FloatField(blank=True, null=True)
    e_r_upmag = models.FloatField(blank=True, null=True)
    r_prad = models.FloatField(blank=True, null=True)
    e_r_prad = models.FloatField(blank=True, null=True)
    r_ora = models.FloatField(blank=True, null=True)
    r_odec = models.FloatField(blank=True, null=True)
    r_dvrad = models.FloatField(blank=True, null=True)
    r_dvell = models.FloatField(blank=True, null=True)
    r_pa = models.FloatField(blank=True, null=True)
    i_flags = models.CharField(max_length=24, blank=True, null=True)
    i_prob = models.IntegerField(blank=True, null=True)
    i_photo = models.IntegerField(blank=True, null=True)
    i_date = models.FloatField(blank=True, null=True)
    i_prime_mag = models.FloatField(blank=True, null=True)
    e_i_prime_mag = models.FloatField(blank=True, null=True)
    i_pmag = models.FloatField(blank=True, null=True)
    e_i_pmag = models.FloatField(blank=True, null=True)
    i_upmag = models.FloatField(blank=True, null=True)
    e_i_upmag = models.FloatField(blank=True, null=True)
    i_prad = models.FloatField(blank=True, null=True)
    e_i_prad = models.FloatField(blank=True, null=True)
    i_ora = models.FloatField(blank=True, null=True)
    i_odec = models.FloatField(blank=True, null=True)
    i_dvrad = models.FloatField(blank=True, null=True)
    i_dvell = models.FloatField(blank=True, null=True)
    i_pa = models.FloatField(blank=True, null=True)
    z_flags = models.CharField(max_length=24, blank=True, null=True)
    z_prob = models.IntegerField(blank=True, null=True)
    z_photo = models.IntegerField(blank=True, null=True)
    z_date = models.FloatField(blank=True, null=True)
    z_prime_mag = models.FloatField(blank=True, null=True)
    e_z_prime_mag = models.FloatField(blank=True, null=True)
    z_pmag = models.FloatField(blank=True, null=True)
    e_z_pmag = models.FloatField(blank=True, null=True)
    z_upmag = models.FloatField(blank=True, null=True)
    e_z_upmag = models.FloatField(blank=True, null=True)
    z_prad = models.FloatField(blank=True, null=True)
    e_z_prad = models.FloatField(blank=True, null=True)
    z_ora = models.FloatField(blank=True, null=True)
    z_odec = models.FloatField(blank=True, null=True)
    z_dvrad = models.FloatField(blank=True, null=True)
    z_dvell = models.FloatField(blank=True, null=True)
    z_pa = models.FloatField(blank=True, null=True)
    pmra = models.FloatField(blank=True, null=True)
    e_pmra = models.FloatField(blank=True, null=True)
    pmdec = models.FloatField(blank=True, null=True)
    e_pmdec = models.FloatField(blank=True, null=True)
    sigra = models.FloatField(blank=True, null=True)
    sigdec = models.FloatField(blank=True, null=True)
    m = models.IntegerField(blank=True, null=True)
    n = models.IntegerField(blank=True, null=True)
    g_o_plate = models.FloatField(blank=True, null=True)
    r_e_plate = models.FloatField(blank=True, null=True)
    g_j_plate = models.FloatField(blank=True, null=True)
    r_f_plate = models.FloatField(blank=True, null=True)
    i_n_plate = models.FloatField(blank=True, null=True)
    zph = models.FloatField(blank=True, null=True)
    e_zph = models.FloatField(blank=True, null=True)
    ave_zph = models.FloatField(blank=True, null=True)
    chi2 = models.FloatField(blank=True, null=True)
    abs_u_mag = models.FloatField(blank=True, null=True)
    abs_g_mag = models.FloatField(blank=True, null=True)
    abs_r_mag = models.FloatField(blank=True, null=True)
    abs_i_mag = models.FloatField(blank=True, null=True)
    abs_z_mag = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "sdss12photoz_q3c"


class TnsQ3C(models.Model):
    tid = models.AutoField(primary_key=True)
    objid = models.IntegerField(blank=True, null=True)
    name_prefix = models.CharField(max_length=4, blank=True, null=True)
    name = models.CharField(max_length=32, blank=True, null=True)
    ra = models.FloatField(blank=True, null=True)
    declination = models.FloatField(blank=True, null=True)
    redshift = models.FloatField(blank=True, null=True)
    typeid = models.IntegerField(blank=True, null=True)
    objtype = models.CharField(max_length=32, blank=True, null=True)
    reporting_groupid = models.IntegerField(blank=True, null=True)
    reporting_group = models.CharField(max_length=32, blank=True, null=True)
    source_groupid = models.IntegerField(blank=True, null=True)
    source_group = models.CharField(max_length=32, blank=True, null=True)
    discoverydate = models.DateTimeField(blank=True, null=True)
    discoverymag = models.FloatField(blank=True, null=True)
    discmagfilter = models.IntegerField(blank=True, null=True)
    filtername = models.CharField(max_length=24, blank=True, null=True)
    reporters = models.CharField(max_length=2048, blank=True, null=True)
    time_received = models.DateTimeField(blank=True, null=True)
    internal_names = models.CharField(max_length=256, blank=True, null=True)
    discovery_ads_bibcode = models.CharField(max_length=256, blank=True, null=True)
    class_ads_bibcodes = models.CharField(max_length=256, blank=True, null=True)
    creationdate = models.DateTimeField(blank=True, null=True)
    lastmodified = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "tns_q3c"


class TwomassQ3C(models.Model):
    ra = models.FloatField(blank=True, null=True)
    decl = models.FloatField(blank=True, null=True)
    err_maj = models.FloatField(blank=True, null=True)
    err_min = models.FloatField(blank=True, null=True)
    err_ang = models.SmallIntegerField(blank=True, null=True)
    designation = models.CharField(max_length=17, blank=True, null=True)
    j_m = models.FloatField(blank=True, null=True)
    j_cmsig = models.FloatField(blank=True, null=True)
    j_msigcom = models.FloatField(blank=True, null=True)
    j_snr = models.FloatField(blank=True, null=True)
    h_m = models.FloatField(blank=True, null=True)
    h_cmsig = models.FloatField(blank=True, null=True)
    h_msigcom = models.FloatField(blank=True, null=True)
    h_snr = models.FloatField(blank=True, null=True)
    k_m = models.FloatField(blank=True, null=True)
    k_cmsig = models.FloatField(blank=True, null=True)
    k_msigcom = models.FloatField(blank=True, null=True)
    k_snr = models.FloatField(blank=True, null=True)
    ph_qual = models.CharField(max_length=3, blank=True, null=True)
    rd_flg = models.CharField(max_length=3, blank=True, null=True)
    bl_flg = models.CharField(max_length=3, blank=True, null=True)
    cc_flg = models.CharField(max_length=3, blank=True, null=True)
    ndet = models.CharField(max_length=6, blank=True, null=True)
    prox = models.FloatField(blank=True, null=True)
    pxpa = models.SmallIntegerField(blank=True, null=True)
    pxcntr = models.IntegerField(blank=True, null=True)
    gal_contam = models.SmallIntegerField(blank=True, null=True)
    mp_flg = models.SmallIntegerField(blank=True, null=True)
    pts_key = models.IntegerField(blank=True, null=True)
    hemis = models.CharField(max_length=1, blank=True, null=True)
    date = models.DateField(blank=True, null=True)
    scan = models.SmallIntegerField(blank=True, null=True)
    glon = models.FloatField(blank=True, null=True)
    glat = models.FloatField(blank=True, null=True)
    x_scan = models.FloatField(blank=True, null=True)
    jdate = models.FloatField(blank=True, null=True)
    j_psfchi = models.FloatField(blank=True, null=True)
    h_psfchi = models.FloatField(blank=True, null=True)
    k_psfchi = models.FloatField(blank=True, null=True)
    j_m_stdap = models.FloatField(blank=True, null=True)
    j_msig_stdap = models.FloatField(blank=True, null=True)
    h_m_stdap = models.FloatField(blank=True, null=True)
    h_msig_stdap = models.FloatField(blank=True, null=True)
    k_m_stdap = models.FloatField(blank=True, null=True)
    k_msig_stdap = models.FloatField(blank=True, null=True)
    dist_edge_ns = models.IntegerField(blank=True, null=True)
    dist_edge_ew = models.IntegerField(blank=True, null=True)
    dist_edge_flg = models.CharField(max_length=2, blank=True, null=True)
    dup_src = models.SmallIntegerField(blank=True, null=True)
    use_src = models.SmallIntegerField(blank=True, null=True)
    a = models.CharField(max_length=1, blank=True, null=True)
    dist_opt = models.FloatField(blank=True, null=True)
    phi_opt = models.SmallIntegerField(blank=True, null=True)
    b_m_opt = models.FloatField(blank=True, null=True)
    vr_m_opt = models.FloatField(blank=True, null=True)
    nopt_mchs = models.SmallIntegerField(blank=True, null=True)
    ext_key = models.IntegerField(blank=True, null=True)
    scan_key = models.IntegerField(blank=True, null=True)
    coadd_key = models.IntegerField(blank=True, null=True)
    coadd = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "twomass_q3c"


class ZtfVarstarQ3C(models.Model):
    id = models.CharField(max_length=22, blank=True, primary_key=True)
    sourceid = models.BigIntegerField(blank=True, null=True)
    radeg = models.FloatField(blank=True, null=True)
    dedeg = models.FloatField(blank=True, null=True)
    per = models.FloatField(blank=True, null=True)
    r21 = models.FloatField(blank=True, null=True)
    phi21 = models.FloatField(blank=True, null=True)
    t0 = models.FloatField(blank=True, null=True)
    gmag = models.FloatField(blank=True, null=True)
    rmag = models.FloatField(blank=True, null=True)
    per_g = models.FloatField(blank=True, null=True)
    per_r = models.FloatField(blank=True, null=True)
    num_g = models.IntegerField(blank=True, null=True)
    num_r = models.IntegerField(blank=True, null=True)
    r21_g = models.FloatField(blank=True, null=True)
    r21_r = models.FloatField(blank=True, null=True)
    phi21_g = models.FloatField(blank=True, null=True)
    phi21_r = models.FloatField(blank=True, null=True)
    r2_g = models.FloatField(blank=True, null=True)
    r2_r = models.FloatField(blank=True, null=True)
    amp_g = models.FloatField(blank=True, null=True)
    amp_r = models.FloatField(blank=True, null=True)
    logfap_g = models.FloatField(blank=True, null=True)
    logfap_r = models.FloatField(blank=True, null=True)
    type = models.CharField(max_length=5, blank=True, null=True)
    dmin_g = models.FloatField(blank=True, null=True)
    dmin_r = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "ztf_varstar_q3c"


## catalog of user-provided host galaxies
class UserGalaxyQ3C(models.Model):
    id = models.AutoField(primary_key=True)
    objname = models.TextField(blank=True, null=True)
    ra = models.FloatField(blank=True, null=True)
    dec = models.FloatField(blank=True, null=True)
    z = models.FloatField(blank=True, null=True)
    z_err = models.FloatField(blank=True, null=True)
    z_pos_err = models.FloatField(blank=True, null=True)
    z_neg_err = models.FloatField(blank=True, null=True)
    z_type = models.TextField(blank=True, null=True)
    lumdist = models.FloatField(blank=True, null=True)
    lumdist_err = models.FloatField(blank=True, null=True)
    lumdist_pos_err = models.FloatField(blank=True, null=True)
    lumdist_neg_err = models.FloatField(blank=True, null=True)
    default_mag = models.FloatField(blank=True, null=True)
    source = models.TextField(blank=True, null=True)
    submitter = models.TextField(blank=True, null=True)  # submitter and original source
    og_id = models.BigIntegerField(blank=True, null=True)

    # managed = True (default, specified here for clarity)
    # --> allow Django to modify this table
    class Meta:
        managed = True
        db_table = "usergalaxy_q3c"


## ScoreFactor: subscores (e.g., 'skymap_score') which are used to compute overall score
class ScoreFactor(models.Model):
    id = models.AutoField(primary_key=True)
    event_candidate = models.ForeignKey(EventCandidate, on_delete=models.CASCADE)
    key = models.CharField(max_length=200)
    value = models.CharField(max_length=200)

    class Meta:
        unique_together = ("event_candidate", "key")


## <catalogname>TargetMatch: tables for storing target : host galaxy associations
class Cosmicflows4TargetMatch(models.Model):
    id = models.AutoField(primary_key=True)
    target = models.ForeignKey(Target, on_delete=models.CASCADE)
    host_galaxy = models.BigIntegerField(blank=False, null=False)
    pcc = models.FloatField(blank=False, null=False)

    class Meta:
        unique_together = ("target", "host_galaxy")
        db_table = "cosmicflows4_targetmatch"


class DesiDr1TargetMatch(models.Model):
    id = models.AutoField(primary_key=True)
    target = models.ForeignKey(Target, on_delete=models.CASCADE)
    host_galaxy = models.BigIntegerField(blank=False, null=False)
    pcc = models.FloatField(blank=False, null=False)

    class Meta:
        unique_together = ("target", "host_galaxy")
        db_table = "desi_dr1_targetmatch"


class GladePlusTargetMatch(models.Model):
    id = models.AutoField(primary_key=True)
    target = models.ForeignKey(Target, on_delete=models.CASCADE)
    host_galaxy = models.BigIntegerField(blank=False, null=False)
    pcc = models.FloatField(blank=False, null=False)

    class Meta:
        unique_together = ("target", "host_galaxy")
        db_table = "glade_plus_targetmatch"


class GwgcTargetMatch(models.Model):
    id = models.AutoField(primary_key=True)
    target = models.ForeignKey(Target, on_delete=models.CASCADE)
    host_galaxy = models.BigIntegerField(blank=False, null=False)
    pcc = models.FloatField(blank=False, null=False)

    class Meta:
        unique_together = ("target", "host_galaxy")
        db_table = "gwgc_targetmatch"


class Hecate1TargetMatch(models.Model):
    id = models.AutoField(primary_key=True)
    target = models.ForeignKey(Target, on_delete=models.CASCADE)
    host_galaxy = models.BigIntegerField(blank=False, null=False)
    pcc = models.FloatField(blank=False, null=False)

    class Meta:
        unique_together = ("target", "host_galaxy")
        db_table = "hecate1_targetmatch"


class Hecate2TargetMatch(models.Model):
    id = models.AutoField(primary_key=True)
    target = models.ForeignKey(Target, on_delete=models.CASCADE)
    host_galaxy = models.BigIntegerField(blank=False, null=False)
    pcc = models.FloatField(blank=False, null=False)

    class Meta:
        unique_together = ("target", "host_galaxy")
        db_table = "hecate2_targetmatch"


class LsDr9NorthTargetMatch(models.Model):
    id = models.AutoField(primary_key=True)
    target = models.ForeignKey(Target, on_delete=models.CASCADE)
    host_galaxy = models.BigIntegerField(blank=False, null=False)
    pcc = models.FloatField(blank=False, null=False)

    class Meta:
        unique_together = ("target", "host_galaxy")
        db_table = "ls_dr9north_targetmatch"


class LsDr10SouthTargetMatch(models.Model):
    id = models.AutoField(primary_key=True)
    target = models.ForeignKey(Target, on_delete=models.CASCADE)
    host_galaxy = models.BigIntegerField(blank=False, null=False)
    pcc = models.FloatField(blank=False, null=False)

    class Meta:
        unique_together = ("target", "host_galaxy")
        db_table = "ls_dr10south_targetmatch"


class NedLvsTargetMatch(models.Model):
    id = models.AutoField(primary_key=True)
    target = models.ForeignKey(Target, on_delete=models.CASCADE)
    host_galaxy = models.BigIntegerField(blank=False, null=False)
    pcc = models.FloatField(blank=False, null=False)

    class Meta:
        unique_together = ("target", "host_galaxy")
        db_table = "nedlvs_targetmatch"


class Ps1GalaxyTargetMatch(models.Model):
    id = models.AutoField(primary_key=True)
    target = models.ForeignKey(Target, on_delete=models.CASCADE)
    host_galaxy = models.BigIntegerField(blank=False, null=False)
    pcc = models.FloatField(blank=False, null=False)

    class Meta:
        unique_together = ("target", "host_galaxy")
        db_table = "ps1_targetmatch"


class Sdss12PhotozTargetMatch(models.Model):
    id = models.AutoField(primary_key=True)
    target = models.ForeignKey(Target, on_delete=models.CASCADE)
    host_galaxy = models.BigIntegerField(blank=False, null=False)
    pcc = models.FloatField(blank=False, null=False)

    class Meta:
        unique_together = ("target", "host_galaxy")
        db_table = "sdss12photoz_targetmatch"


class UserGalaxyTargetMatch(models.Model):
    id = models.AutoField(primary_key=True)
    target = models.ForeignKey(Target, on_delete=models.CASCADE)
    host_galaxy = models.BigIntegerField(blank=False, null=False)
    pcc = models.FloatField(blank=False, null=False)

    class Meta:
        unique_together = ("target", "host_galaxy")
        db_table = "usergalaxy_targetmatch"
