"""
grids.py — loading and selecting simulation grids.

A "grid" is the population of simulated kilonova light curves the scorer
compares an observation against. It is generated by :mod:`.simulation` (redback
/ bilby) and stored as **Parquet** under ``KilonovaScorer/grids/``.

Parquet rather than CSV: the grids are large (90M rows for 10k simulations) and
purely numeric. Column-wise typed binary storage compresses ~14x versus CSV and
lets a reader touch only the columns and row groups it needs -- the four
columns the scorer actually uses load in ~0.2 s out of a 1.4 GB file, where the
equivalent CSV was ~20 GB and minutes to parse.

Because the model is evaluated at a redshift, a grid is tied to the luminosity
distance it was generated at. Working in absolute magnitude removes the distance
modulus but *not* the k-correction (a fixed filter samples rest-frame
lambda/(1+z)) or time dilation (an epoch t maps to t/(1+z)). Both are band- and
epoch-dependent, so they change the shape of the magnitude distribution in each
(band, time-bin) cell rather than shifting it -- and a shape change cannot be
corrected after the fact.

That argued for a distance ladder -- a rung every few hundred Mpc, the nearest
one picked per candidate. It was built and then removed on 2026-08-12: there is
one 259 Mpc grid, named in ``DEFAULT_KILONOVA_PARAMS["grid_path"]``, and every
candidate is scored against it whatever its own distance. **This is a known
defect, not a resolved question** -- IMPROVEMENTS.md section 18 has the measured
size of the error and the rung spacing it would take to fix. Grids are still
tagged with their distance in ``kn_grid_axis``, so selection can come back
without regenerating anything.

    from KilonovaScorer.grids import load_grid, resolve_grid, available_grids

    available_grids()                              # what's in the store
    grid = load_grid(resolve_grid("simulations_..._259Mpc_30d"))

Two backends
------------
A grid can also live in a local PostgreSQL database instead of a file -- one
row per lightcurve, magnitudes as a ``bytea``, benchmarked in ``DB.md`` and
implemented in :mod:`.grid_db`. It reads a single band in 3.0 s / 847 MB where
the Parquet file needs 8.5 s / 2,840 MB, because the file's row groups each
contain every band so a band filter prunes nothing.

Everything in this module dispatches on ``TROVE_GRID_BACKEND``, and the three
public entry points return and accept the same things either way -- a grid is
identified by a :class:`Path` under Parquet and a :class:`GridRef` under
Postgres, both of which have a ``.name`` and hash. Parquet stays the default,
so nothing changes until the environment says so:

    export TROVE_GRID_BACKEND=postgres
    export TROVE_GRID_DSN='postgresql://trove@127.0.0.1:5433/kn_grids'
"""

from __future__ import annotations

import logging
import os
import re
from collections import OrderedDict
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Sequence, Union

import numpy as np
import pandas as pd

from .core import FILTER_LOOKUP

logger = logging.getLogger(__name__)

#: Retained as a constant because callers still branch on it, but there is only
#: one backend now: grids are written straight into Postgres by the simulator
#: and read back by :mod:`.grid_db`. ``TROVE_GRID_BACKEND`` is honoured only to
#: reject a stale ``=parquet`` loudly rather than silently ignoring it -- that
#: setting used to select a real code path, and a deployment still exporting it
#: is configured for a backend that no longer exists.
GRID_BACKEND = "postgres"

_requested_backend = (os.environ.get("TROVE_GRID_BACKEND") or "").strip().lower()
if _requested_backend and _requested_backend != "postgres":
    raise RuntimeError(
        f"TROVE_GRID_BACKEND={_requested_backend!r} is no longer supported. The "
        "Parquet backend has been removed; grids live in the Postgres store "
        "addressed by TROVE_GRID_DSN. Unset TROVE_GRID_BACKEND or set it to "
        "'postgres'."
    )


@dataclass(frozen=True)
class GridRef:
    """A grid in the database, standing where a :class:`Path` stands otherwise.

    Frozen so it is hashable: the scoring loop buckets candidates into a dict
    keyed on their grid, and sorts those keys by distance, so whatever
    identifies a grid has to work as a dict key. ``name`` mirrors
    ``Path.name`` for the sake of log lines that report which grid was used.
    """

    name: str
    distance_mpc: float
    backend: str = "postgres"
    #: Last epoch the grid covers, in days. NaN when unknown (the Parquet
    #: backend does not read it). Selection uses it to reject a rung that does
    #: not reach the epochs being scored -- a 10-day rung and a 30-day rung at
    #: the same distance are *not* interchangeable.
    t_max: float = float("nan")

    def __str__(self) -> str:
        return self.name


#: Either kind of grid identifier.
GridId = Union[Path, GridRef]


def resolve_grid(spec) -> GridId:
    """Normalise a grid identifier to a :class:`Path` or a :class:`GridRef`.

    Strings are ambiguous -- a filename under Parquet, a grid name under
    Postgres -- so they are read according to the active backend. Anything
    already resolved passes through, which lets a caller pin one backend's grid
    explicitly regardless of the default.
    """
    if isinstance(spec, (GridRef, Path)):
        return spec
    if GRID_BACKEND == "postgres":
        from . import grid_db

        _axis, distance, _n = grid_db.grid_axis(str(spec))
        return GridRef(name=str(spec), distance_mpc=distance)
    return Path(spec)


def grid_name(spec) -> str:
    """Display name of a grid, whichever backend identifies it."""
    return getattr(spec, "name", None) or str(spec)

#: Where grids live. Defaults to a gitignored directory inside the package --
#: they are generated artifacts, not source -- but the ladder is ~12 GB, which
#: is often better kept off the WSL filesystem entirely. Set ``TROVE_GRID_DIR``
#: to relocate it:
#:
#:     export TROVE_GRID_DIR=/mnt/c/Users/<you>/Trove-Research/grids
#:
#: Anything that loads grids (the Django app included) must have this set, or it
#: will look in the package directory and find nothing.
GRID_DIR = Path(
    os.environ.get("TROVE_GRID_DIR") or (Path(__file__).resolve().parent / "grids")
)

#: Columns the scorer reads. Everything else in a grid (model parameters, the
#: apparent magnitude, IR bands) is only needed for posterior/diagnostic plots,
#: so it is left on disk unless explicitly requested.
SCORING_COLUMNS = ("sample_id", "band", "time", "absolute_magnitude")

#: Band names in a grid that map to a band the scorer models.
MODELLED_SIM_BANDS = tuple(sorted(FILTER_LOOKUP))

#: Absolute magnitudes fainter than this are model artifacts, not kilonovae:
#: redback returns huge magnitudes where a component's flux underflows, and
#: garbage at exactly t=0 where the model is undefined. Left in, they distort
#: the KDE the entire score is built on.
MAX_ABS_MAG = 0.0

#: Distance parsed out of a grid NAME (``..._259Mpc``) as a fallback; the
#: authoritative value is ``kn_grid_axis.distance_mpc``.
_DISTANCE_RE = re.compile(r"(\d+(?:\.\d+)?)\s*mpc", re.IGNORECASE)

#: Rows of ``redshift`` sampled to identify a loaded grid's distance. A grid is
#: generated at one redshift, so this only needs to beat any leading NaNs.
_Z_SAMPLE_ROWS = 1000

#: Ceiling on the combined size of cached grids, in bytes.
#:
#: :func:`load_grid` keys its cache on (path, columns, bands, time cuts, mode),
#: and a scoring run walks through many band combinations -- one per distinct
#: set of filters a candidate was observed in. Unbounded, *every* combination
#: is retained for the life of the process. That is invisible in a script that
#: exits, and fatal under ``manage.py runserver``, which lives for days: the
#: resident set only ever grows, and on WSL the OOM kill that ends it takes the
#: whole VM -- editor included -- with it.
#:
#: A single band of a 40M-row rung is ~0.4 GB, so the default holds a working
#: set of a few band combinations. Override with ``TROVE_GRID_CACHE_BYTES``;
#: 0 disables caching entirely.
GRID_CACHE_BYTES = int(os.environ.get("TROVE_GRID_CACHE_BYTES") or 2_000_000_000)

#: key -> (frame, size_in_bytes), least-recently-used first so eviction pops
#: from the front. Sizes are measured once on insert -- ``memory_usage(deep=
#: True)`` walks the string column, which is not something to repeat on every
#: cache hit.
_CACHE: "OrderedDict[tuple, tuple[pd.DataFrame, int]]" = OrderedDict()


def _cache_get(key):
    """Cached frame for ``key``, marked most-recently-used, or None."""
    entry = _CACHE.get(key)
    if entry is None:
        return None
    _CACHE.move_to_end(key)
    return entry[0]


def _cache_put(key, df: pd.DataFrame) -> None:
    """Cache ``df``, evicting least-recently-used frames to stay under budget.

    A frame bigger than the entire budget is not cached at all: admitting it
    would evict everything else and still leave the cache over its ceiling.
    """
    if GRID_CACHE_BYTES <= 0:
        return
    size = int(df.memory_usage(deep=True).sum())
    if size > GRID_CACHE_BYTES:
        logger.info(
            "Not caching %s (%.0f MB): larger than the %.0f MB cache budget",
            df.attrs.get("name", "grid"), size / 1e6, GRID_CACHE_BYTES / 1e6,
        )
        return

    _CACHE[key] = (df, size)
    _CACHE.move_to_end(key)

    total = sum(sz for _, sz in _CACHE.values())
    while total > GRID_CACHE_BYTES and len(_CACHE) > 1:
        _, (evicted, evicted_size) = _CACHE.popitem(last=False)
        total -= evicted_size
        logger.info(
            "Grid cache over budget: evicted %s (%.0f MB), %.0f MB now held",
            evicted.attrs.get("name", "grid"), evicted_size / 1e6, total / 1e6,
        )


def _distance_from_redshift(z: float) -> float:
    from astropy.cosmology import Planck18

    return float(Planck18.luminosity_distance(float(z)).value)


def grid_distance_mpc(source) -> float:
    """Luminosity distance a grid was generated at, in Mpc.

    Accepts a :class:`GridRef` or a loaded DataFrame. The store keeps the
    distance in ``kn_grid_axis`` alongside the time axis, so this is a column
    read -- no redshift sampling, no filename parsing, and no risk of the
    3 GB decompression the Parquet path had to work around.
    """
    if isinstance(source, GridRef):
        return float(source.distance_mpc)

    if isinstance(source, pd.DataFrame):
        if "redshift" in source.columns:
            # head(_Z_SAMPLE_ROWS), not the whole column: on a loaded rung this
            # is tens of millions of rows holding one repeated value.
            z = source["redshift"].head(_Z_SAMPLE_ROWS).dropna()
            if len(z):
                return _distance_from_redshift(np.median(z))
        return float(source.attrs.get("distance_mpc", np.nan))

    # A bare name: ask the store.
    try:
        from . import grid_db

        return float(grid_db.grid_axis(str(source))[1])
    except Exception:  # noqa: BLE001 - unknown grid, or no store configured
        return float("nan")


#: Memoised inventory. Deliberately not dropped by :func:`clear_cache`, which
#: runs between chunks to release grid frames -- this is a handful of rows, and
#: the set of grids cannot change while a score is running.
_INVENTORY: "Optional[pd.DataFrame]" = None


def available_grids(directory=None, refresh: bool = False) -> pd.DataFrame:
    """Inventory of the grids in the store: ``path``, ``distance_mpc``, ``size_mb``.

    Sorted by distance. ``path`` holds a :class:`GridRef` -- a name, not a
    filesystem path -- and ``size_mb`` is the size of the magnitude column.

    Cached for the life of the process. Grids are written by an ingest, never by
    scoring, so the set cannot change under a running score, and re-reading it
    was costing one round trip and one aggregate *per candidate* back when
    selection called this before choosing a rung. Against the grid in
    ``catalogs`` that was 3.15 s x 457 candidates -- roughly 24 minutes to
    re-answer a question with one possible answer. Pass ``refresh=True`` after
    an ingest.

    ``directory`` is accepted and ignored. It selected a folder of Parquet
    rungs, which no longer exist; kept in the signature so the handful of
    callers that pass it keep working rather than raising a TypeError far from
    the cause.
    """
    global _INVENTORY

    if directory is not None:
        logger.warning(
            "available_grids(directory=%r) ignored: grids are in the Postgres "
            "store, not on disk.", directory,
        )
    if _INVENTORY is None or refresh:
        from . import grid_db

        _INVENTORY = grid_db.available_grids_db()
    # a copy: callers index and sort this, and a mutation would poison the cache
    return _INVENTORY.copy()


def load_grid(
    path,
    columns: Optional[Sequence[str]] = SCORING_COLUMNS,
    bands: Optional[Sequence[str]] = None,
    min_time: float = 0.0,
    max_time: Optional[float] = None,
    max_abs_mag: float = MAX_ABS_MAG,
    add_filter_mapped: bool = True,
    use_cache: bool = True,
    mode: str = "survey",
    max_rows: Optional[int] = 80_000_000,
) -> pd.DataFrame:
    """Load a simulation grid from Parquet (or CSV) and normalize it.

    Parameters
    ----------
    path
        Grid identifier: a :class:`GridRef`, or a name resolvable in the
        store. Anything else raises -- there is no file to load.
    columns
        Columns to read. Defaults to the four the scorer needs -- pass ``None``
        for everything (model parameters included, for posterior plots).
    bands
        Grid band names to keep. ``None`` (the default in ``survey`` mode) keeps
        every band in the grid. Applied as a Parquet row-group filter, so
        unwanted bands are never read off disk.
    mode
        ``'survey'`` keys on the grid's own bandpass ids, so an observation is
        matched to simulations through the same filter. ``'canonical'``
        collapses onto g/r/i/z via KilonovaSCORER's ``FILTER_LOOKUP``, for
        LSST-only grids.
    min_time, max_abs_mag
        Drop ``time <= min_time`` (models are undefined at t=0 and return
        absurd magnitudes) and ``absolute_magnitude > max_abs_mag`` (flux
        underflow artifacts at late times). Both distort the KDE if left in.
    max_time
        Drop ``time > max_time``. ``None`` (the default) keeps the full time
        axis. This is a *memory* control, not a science one: ``kilonovascorer_v3``
        only ever reads the time bins spanned by the observations, so simulation
        rows beyond the last epoch are loaded and binned for nothing. Set it
        slightly above the largest ``time_after_gw`` you intend to score (one
        ``time_bin_width`` of headroom is enough -- the scorer's last bin ends
        at ``t_last + bin_width``) and the result is unchanged.

        Note the ceiling: :func:`.simulation.simulate_kilonova` defaults to
        ``TIME = np.linspace(0, 10, 1000)``, so a grid covers **0-10 days** at
        0.01 d resolution -- verified against the 400 Mpc rung, whose stored
        row-group statistics give a time range of 0.0 to 10.0. ``max_time``
        above 10 is therefore a no-op, and *observations* past 10 days cannot be
        scored at all: they fall outside every time bin the grid provides and
        the scorer drops them, which is why ``n_obs_supplied`` can greatly
        exceed ``n_obs_scored``. Cut the photometry at 10 days upstream
        (``dt_max``) rather than paying to fetch and convert epochs no grid can
        score.
    add_filter_mapped
        Add the canonical ``g-band``/``r-band``/... column the scorer keys on.
    max_rows
        Refuse to materialise more than this many rows when no ``bands`` filter
        is given. Guards against loading a whole 380M-row rung, which needs more
        memory than the machine has. ``None`` disables the check.

    Returns
    -------
    pd.DataFrame
        With ``attrs['name']`` and ``attrs['distance_mpc']`` set.
    """
    path = resolve_grid(path)

    if isinstance(path, GridRef):
        # The database backend. `columns` and `max_rows` have no analogue: the
        # store holds exactly the four scoring columns, and a read is bounded
        # by the bands and time window asked for rather than needing a guard
        # against materialising the whole rung.
        from . import grid_db

        key = (
            "postgres", path.name, tuple(bands or ()),
            min_time, max_time, max_abs_mag, mode, add_filter_mapped,
        )
        if use_cache:
            cached = _cache_get(key)
            if cached is not None:
                return cached
        df = grid_db.load_grid_db(
            path.name, bands=bands, min_time=min_time, max_time=max_time,
            max_abs_mag=max_abs_mag, add_filter_mapped=add_filter_mapped, mode=mode,
        )
        if use_cache:
            _cache_put(key, df)
        return df

    raise TypeError(
        f"load_grid received {path!r}. Grids live in the Postgres store and are "
        "identified by name, not by path -- there is no file to load. List what "
        "is available with `available_grids()`, or build a rung with "
        "`KilonovaScorer/generate_rung.py --distance <Mpc>`."
    )


def clear_cache() -> None:
    """Drop cached grids (they are hundreds of MB each)."""
    _CACHE.clear()
