"""
grids.py — loading and selecting simulation grids.

A "grid" is the population of simulated kilonova light curves the scorer
compares an observation against. It is generated by :mod:`.simulation` (redback
/ bilby) and stored as **Parquet** under ``KilonovaScorer/grids/``.

Parquet rather than CSV: the grids are large (90M rows for 10k simulations) and
purely numeric. Column-wise typed binary storage compresses ~14x versus CSV and
lets a reader touch only the columns and row groups it needs -- the four
columns the scorer actually uses load in ~0.2 s out of a 1.4 GB file, where the
equivalent CSV was ~20 GB and minutes to parse.

Because the model is evaluated at a redshift, a grid is tied to the luminosity
distance it was generated at. Working in absolute magnitude removes the distance
modulus but *not* the k-correction (a fixed filter samples rest-frame
lambda/(1+z)) or time dilation (an epoch t maps to t/(1+z)). Both are band- and
epoch-dependent, so they change the shape of the magnitude distribution in each
(band, time-bin) cell rather than shifting it -- and a shape change cannot be
corrected after the fact. Grids therefore come in a distance ladder, and
:func:`grid_for_distance` picks the closest rung to a candidate's distance. See
``generate_ladder.py`` for the derivation of the rung spacing.

    from KilonovaScorer.grids import load_grid, grid_for_distance, available_grids

    available_grids()                       # what's on disk
    grid = load_grid(grid_for_distance(310))  # nearest grid to 310 Mpc
"""

from __future__ import annotations

import logging
import os
import re
from collections import OrderedDict
from pathlib import Path
from typing import List, Optional, Sequence

import numpy as np
import pandas as pd

from .core import FILTER_LOOKUP

logger = logging.getLogger(__name__)

#: Where grids live. Defaults to a gitignored directory inside the package --
#: they are generated artifacts, not source -- but the ladder is ~12 GB, which
#: is often better kept off the WSL filesystem entirely. Set ``TROVE_GRID_DIR``
#: to relocate it:
#:
#:     export TROVE_GRID_DIR=/mnt/c/Users/<you>/Trove-Research/grids
#:
#: Anything that loads grids (the Django app included) must have this set, or it
#: will look in the package directory and find nothing.
GRID_DIR = Path(
    os.environ.get("TROVE_GRID_DIR") or (Path(__file__).resolve().parent / "grids")
)

#: Columns the scorer reads. Everything else in a grid (model parameters, the
#: apparent magnitude, IR bands) is only needed for posterior/diagnostic plots,
#: so it is left on disk unless explicitly requested.
SCORING_COLUMNS = ("sample_id", "band", "time", "absolute_magnitude")

#: Band names in a grid that map to a band the scorer models.
MODELLED_SIM_BANDS = tuple(sorted(FILTER_LOOKUP))

#: Absolute magnitudes fainter than this are model artifacts, not kilonovae:
#: redback returns huge magnitudes where a component's flux underflows, and
#: garbage at exactly t=0 where the model is undefined. Left in, they distort
#: the KDE the entire score is built on.
MAX_ABS_MAG = 0.0

#: ``..._259Mpc.parquet`` / ``grid_400mpc.parquet`` -- distance in the filename.
_DISTANCE_RE = re.compile(r"(\d+(?:\.\d+)?)\s*mpc", re.IGNORECASE)

#: Rows of ``redshift`` sampled to identify a loaded grid's distance. A grid is
#: generated at one redshift, so this only needs to beat any leading NaNs.
_Z_SAMPLE_ROWS = 1000

#: Ceiling on the combined size of cached grids, in bytes.
#:
#: :func:`load_grid` keys its cache on (path, columns, bands, time cuts, mode),
#: and a scoring run walks through many band combinations -- one per distinct
#: set of filters a candidate was observed in. Unbounded, *every* combination
#: is retained for the life of the process. That is invisible in a script that
#: exits, and fatal under ``manage.py runserver``, which lives for days: the
#: resident set only ever grows, and on WSL the OOM kill that ends it takes the
#: whole VM -- editor included -- with it.
#:
#: A single band of a 40M-row rung is ~0.4 GB, so the default holds a working
#: set of a few band combinations. Override with ``TROVE_GRID_CACHE_BYTES``;
#: 0 disables caching entirely.
GRID_CACHE_BYTES = int(os.environ.get("TROVE_GRID_CACHE_BYTES") or 2_000_000_000)

#: key -> (frame, size_in_bytes), least-recently-used first so eviction pops
#: from the front. Sizes are measured once on insert -- ``memory_usage(deep=
#: True)`` walks the string column, which is not something to repeat on every
#: cache hit.
_CACHE: "OrderedDict[tuple, tuple[pd.DataFrame, int]]" = OrderedDict()


def _cache_get(key):
    """Cached frame for ``key``, marked most-recently-used, or None."""
    entry = _CACHE.get(key)
    if entry is None:
        return None
    _CACHE.move_to_end(key)
    return entry[0]


def _cache_put(key, df: pd.DataFrame) -> None:
    """Cache ``df``, evicting least-recently-used frames to stay under budget.

    A frame bigger than the entire budget is not cached at all: admitting it
    would evict everything else and still leave the cache over its ceiling.
    """
    if GRID_CACHE_BYTES <= 0:
        return
    size = int(df.memory_usage(deep=True).sum())
    if size > GRID_CACHE_BYTES:
        logger.info(
            "Not caching %s (%.0f MB): larger than the %.0f MB cache budget",
            df.attrs.get("name", "grid"), size / 1e6, GRID_CACHE_BYTES / 1e6,
        )
        return

    _CACHE[key] = (df, size)
    _CACHE.move_to_end(key)

    total = sum(sz for _, sz in _CACHE.values())
    while total > GRID_CACHE_BYTES and len(_CACHE) > 1:
        _, (evicted, evicted_size) = _CACHE.popitem(last=False)
        total -= evicted_size
        logger.info(
            "Grid cache over budget: evicted %s (%.0f MB), %.0f MB now held",
            evicted.attrs.get("name", "grid"), evicted_size / 1e6, total / 1e6,
        )


def _distance_from_redshift(z: float) -> float:
    from astropy.cosmology import Planck18

    return float(Planck18.luminosity_distance(float(z)).value)


def grid_distance_mpc(source) -> float:
    """Luminosity distance a grid was generated at, in Mpc.

    Accepts a loaded DataFrame or a path. A grid is generated at a single
    redshift, so one row answers the question and only one row group is ever
    read -- ``pd.read_parquet(path, columns=["redshift"]).head(1)`` would
    decompress the whole 380M-row column (~3 GB) to look at its first element,
    which is enough to OOM the machine when it happens inside a loop.

    Falls back to the filename when there is no ``redshift`` column, and returns
    NaN if neither is available.
    """
    if isinstance(source, pd.DataFrame):
        if "redshift" in source.columns:
            # head(_Z_SAMPLE_ROWS), not the whole column: on a loaded rung this
            # is tens of millions of rows holding one repeated value.
            z = source["redshift"].head(_Z_SAMPLE_ROWS).dropna()
            if len(z):
                return _distance_from_redshift(np.median(z))
        return float(source.attrs.get("distance_mpc", np.nan))

    path = Path(source)
    try:
        if _is_parquet(path):
            import pyarrow.parquet as pq

            pf = pq.ParquetFile(path)
            if "redshift" not in pf.schema_arrow.names or pf.num_row_groups == 0:
                raise KeyError("redshift")
            head = pf.read_row_group(0, columns=["redshift"]).slice(0, 1).to_pandas()
        else:
            head = pd.read_csv(path, usecols=["redshift"], nrows=1)
        if len(head):
            return _distance_from_redshift(head["redshift"].iloc[0])
    except Exception:  # noqa: BLE001 - fall through to the filename
        pass

    match = _DISTANCE_RE.search(path.stem)
    return float(match.group(1)) if match else np.nan


def _is_parquet(path: Path) -> bool:
    return path.suffix.lower() in (".parquet", ".pq")


def available_grids(directory=None) -> pd.DataFrame:
    """Inventory of grids on disk: ``path``, ``distance_mpc``, ``size_mb``.

    Sorted by distance so the ladder is obvious at a glance.
    """
    directory = Path(directory) if directory else GRID_DIR
    if not directory.exists():
        return pd.DataFrame(columns=["path", "distance_mpc", "size_mb"])

    rows = []
    for path in sorted(list(directory.glob("*.parquet")) + list(directory.glob("*.csv"))):
        rows.append(
            {
                "path": path,
                "distance_mpc": grid_distance_mpc(path),
                "size_mb": path.stat().st_size / 1e6,
            }
        )
    out = pd.DataFrame(rows)
    return out.sort_values("distance_mpc").reset_index(drop=True) if len(out) else out


def grid_for_distance(dist_mpc: float, directory=None, max_frac_offset: Optional[float] = None) -> Path:
    """Path of the grid closest in luminosity distance to ``dist_mpc``.

    ``max_frac_offset`` optionally rejects a match that is too far away in
    fractional terms -- e.g. ``0.5`` refuses to score a 1500 Mpc candidate
    against a 400 Mpc grid, which is the case where you want to generate a new
    grid rather than silently use a bad one.
    """
    grids = available_grids(directory)
    grids = grids[grids["distance_mpc"].notna()] if len(grids) else grids
    if grids.empty:
        raise FileNotFoundError(
            f"No grids found in {Path(directory) if directory else GRID_DIR}. "
            "Generate one with KilonovaScorer.simulation.simulate_kilonova()."
        )
    if not np.isfinite(dist_mpc) or dist_mpc <= 0:
        raise ValueError(f"Cannot select a grid for distance {dist_mpc}")

    best = grids.iloc[(grids["distance_mpc"] - dist_mpc).abs().argmin()]
    offset = abs(best["distance_mpc"] - dist_mpc) / dist_mpc
    if max_frac_offset is not None and offset > max_frac_offset:
        raise ValueError(
            f"Nearest grid is {best['distance_mpc']:.0f} Mpc for a candidate at "
            f"{dist_mpc:.0f} Mpc ({offset:.0%} off, limit {max_frac_offset:.0%}). "
            "Generate a grid at this distance."
        )
    logger.info(
        "Candidate at %.0f Mpc -> %s (%.0f Mpc, %.0f%% off)",
        dist_mpc, best["path"].name, best["distance_mpc"], offset * 100,
    )
    return best["path"]


def load_grid(
    path,
    columns: Optional[Sequence[str]] = SCORING_COLUMNS,
    bands: Optional[Sequence[str]] = None,
    min_time: float = 0.0,
    max_time: Optional[float] = None,
    max_abs_mag: float = MAX_ABS_MAG,
    add_filter_mapped: bool = True,
    use_cache: bool = True,
    mode: str = "survey",
    max_rows: Optional[int] = 80_000_000,
) -> pd.DataFrame:
    """Load a simulation grid from Parquet (or CSV) and normalize it.

    Parameters
    ----------
    path
        Grid file. ``.parquet`` is the expected format; ``.csv`` still works for
        grids produced before the switch.
    columns
        Columns to read. Defaults to the four the scorer needs -- pass ``None``
        for everything (model parameters included, for posterior plots).
    bands
        Grid band names to keep. ``None`` (the default in ``survey`` mode) keeps
        every band in the grid. Applied as a Parquet row-group filter, so
        unwanted bands are never read off disk.
    mode
        ``'survey'`` keys on the grid's own bandpass ids, so an observation is
        matched to simulations through the same filter. ``'canonical'``
        collapses onto g/r/i/z via KilonovaSCORER's ``FILTER_LOOKUP``, for
        LSST-only grids.
    min_time, max_abs_mag
        Drop ``time <= min_time`` (models are undefined at t=0 and return
        absurd magnitudes) and ``absolute_magnitude > max_abs_mag`` (flux
        underflow artifacts at late times). Both distort the KDE if left in.
    max_time
        Drop ``time > max_time``. ``None`` (the default) keeps the full time
        axis. This is a *memory* control, not a science one: ``kilonovascorer_v3``
        only ever reads the time bins spanned by the observations, so simulation
        rows beyond the last epoch are loaded and binned for nothing. Set it
        slightly above the largest ``time_after_gw`` you intend to score (one
        ``time_bin_width`` of headroom is enough -- the scorer's last bin ends
        at ``t_last + bin_width``) and the result is unchanged.

        Note the ceiling: :func:`.simulation.simulate_kilonova` defaults to
        ``TIME = np.linspace(0, 10, 1000)``, so a grid covers **0-10 days** at
        0.01 d resolution -- verified against the 400 Mpc rung, whose parquet
        row-group statistics give a time range of 0.0 to 10.0. ``max_time``
        above 10 is therefore a no-op, and *observations* past 10 days cannot be
        scored at all: they fall outside every time bin the grid provides and
        the scorer drops them, which is why ``n_obs_supplied`` can greatly
        exceed ``n_obs_scored``. Cut the photometry at 10 days upstream
        (``dt_max``) rather than paying to fetch and convert epochs no grid can
        score.
    add_filter_mapped
        Add the canonical ``g-band``/``r-band``/... column the scorer keys on.
    max_rows
        Refuse to materialise more than this many rows when no ``bands`` filter
        is given. Guards against loading a whole 380M-row rung, which needs more
        memory than the machine has. ``None`` disables the check.

    Returns
    -------
    pd.DataFrame
        With ``attrs['name']`` and ``attrs['distance_mpc']`` set.
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(
            f"Simulation grid not found: {path}\n"
            f"Available grids in {GRID_DIR}:\n{available_grids()}"
        )

    key = (
        str(path.resolve()), path.stat().st_mtime,
        tuple(columns or ()), tuple(bands or ()), min_time, max_time, max_abs_mag, mode,
    )
    if use_cache:
        cached = _cache_get(key)
        if cached is not None:
            return cached

    cols = list(columns) if columns else None
    cols_read = cols
    if cols and "redshift" not in cols and not _is_parquet(path):
        # A grid is generated at one redshift, so this column is tens of
        # millions of copies of a single value -- 376 MB on a 47M-row selection,
        # read and then immediately dropped. For Parquet the distance comes from
        # the file instead (one row group), so it is never read. CSV has no
        # cheap way to sample one value, so there it still rides along.
        cols_read = cols + ["redshift"]

    if _is_parquet(path):
        import pyarrow.parquet as pq

        pf = pq.ParquetFile(path)
        # A full ladder rung is 380M rows, ~15 GB once materialised as a
        # DataFrame -- more than the machine has, and an OOM kill takes the
        # whole WSL VM (and the editor attached to it) with it. Nothing in the
        # scorer needs every band at once: pass the bands the candidate was
        # observed in. Raise rather than warn, because by the time a warning is
        # visible the allocation is already under way.
        if max_rows and not bands and pf.metadata.num_rows > max_rows:
            raise MemoryError(
                f"{path.name} has {pf.metadata.num_rows:,} rows; loading every band at "
                f"once needs roughly {pf.metadata.num_rows * 40 / 1e9:.0f} GB of RAM.\n"
                f"Pass bands=[...] to read only what you need (one band is "
                f"~{pf.metadata.num_rows // max(1, len(MODELLED_SIM_BANDS)):,} rows), or "
                f"raise max_rows if you really do have the memory."
            )
        available = set(pf.schema_arrow.names)
        if cols_read:
            cols_read = [c for c in cols_read if c in available]
        # Both predicates are pushed down so the rows are dropped by the parquet
        # reader rather than after a full materialisation -- the point of the
        # exercise is never holding the unwanted rows in memory at all.
        filters = []
        if bands and "band" in available:
            filters.append(("band", "in", list(bands)))
        if max_time is not None and "time" in available:
            filters.append(("time", "<=", float(max_time)))
        # Stream the read in batches rather than materialising one table.
        #
        # `pq.read_table(...).to_pandas(self_destruct=True)` builds the entire
        # filtered result as Arrow first -- at float64, and with `band` as
        # strings -- and only then hands it to pandas for the float32/categorical
        # narrowing below. The peak is therefore the *wide* representation of the
        # whole selection, several times the frame that comes back: measured on
        # this 380M-row rung, a 5-band selection (47M rows, an 865 MB frame)
        # peaked over 4.5 GB and tripped the OOM guard, even though it fits in
        # memory comfortably once narrowed.
        #
        # Scanning batch by batch and narrowing each one before it is retained
        # bounds the peak to (final frame + one batch + the concat copy). Same
        # rows, same dtypes, same order -- the scanner reads row groups in file
        # order and the filters are the identical pushdown expression.
        #
        # This is what makes a load that cannot be split by band survivable: a
        # single candidate observed in more bands than `max_bands_per_load`
        # forces all of them into one load, so the reader has to be the thing
        # that stays bounded.
        import pyarrow.dataset as pds

        try:
            expr = pq.filters_to_expression(filters) if filters else None
        except AttributeError:  # pyarrow < 13
            expr = pq._filters_to_expression(filters) if filters else None

        # Fixing the category list up front keeps `band` categorical in every
        # batch, so concat can stay categorical. As plain strings this column is
        # ~2 GB on a 47M-row selection -- more than everything else combined.
        cats = sorted(bands) if bands else None

        # Readahead has to be pinned down or streaming loses to read_table. The
        # scanner defaults to 16 batches x 4 fragments in flight, and since every
        # row group here contains every band, the band filter prunes nothing --
        # each prefetched batch is a fully decompressed row group. Measured on a
        # 1-band selection (a 131 MB frame): 3.29 GB peak at the defaults against
        # 14.7 s / 1.26 GB for the old read_table path. One batch at a time, one
        # fragment at a time, is what actually bounds the read.
        scanner = pds.dataset(path, format="parquet").scanner(
            columns=cols_read,
            filter=expr,
            batch_size=250_000,
            batch_readahead=1,
            fragment_readahead=1,
            use_threads=False,
        )
        parts = []
        for batch in scanner.to_batches():
            if batch.num_rows == 0:
                continue
            part = batch.to_pandas(self_destruct=True, split_blocks=True)
            del batch
            for col in ("time", "absolute_magnitude"):
                if col in part.columns:
                    part[col] = part[col].astype("float32")
            if "sample_id" in part.columns:
                part["sample_id"] = part["sample_id"].astype("int32")
            if cats is not None and "band" in part.columns:
                part["band"] = pd.Categorical(part["band"], categories=cats)
            parts.append(part)

        if not parts:
            raise ValueError(
                f"Grid {path.name} returned no rows for bands={list(bands or [])}, "
                f"max_time={max_time}"
            )
        df = pd.concat(parts, ignore_index=True, copy=False) if len(parts) > 1 else parts[0]
        del parts  # drop the per-batch references so concat's inputs can be freed
    else:
        available = set(pd.read_csv(path, nrows=0).columns)
        if cols_read:
            cols_read = [c for c in cols_read if c in available]
        df = pd.read_csv(path, usecols=cols_read)
        if bands and "band" in df.columns:
            df = df[df["band"].isin(bands)]
        if max_time is not None and "time" in df.columns:
            df = df[df["time"] <= max_time]

    n_read = len(df)
    missing = {"sample_id", "time", "absolute_magnitude"} - set(df.columns)
    if missing:
        raise ValueError(f"Grid {path.name} is missing required column(s): {sorted(missing)}")

    distance = grid_distance_mpc(df if "redshift" in df.columns else path)
    df = df.drop(columns=[c for c in ("redshift",) if cols and c not in cols and c in df.columns])

    # Narrow the two big float columns; float32 is ~7 significant digits, far
    # beyond the precision of a simulated magnitude, and halves memory.
    for col in ("time", "absolute_magnitude"):
        if col in df.columns:
            df[col] = df[col].astype("float32")
    if "band" in df.columns:
        df["band"] = df["band"].astype("category")

    if add_filter_mapped and "band" in df.columns:
        if mode == "survey":
            # The grid's own bandpass ids ARE the matching key: an observation
            # through atlaso is scored against simulations through atlaso.
            df["filter_mapped"] = df["band"]
        else:
            # Legacy: collapse onto canonical g/r/i/z. Map on the (few) distinct
            # band names, not row-by-row, and keep the result categorical -- as
            # plain strings this column alone is ~2 GB on a 37M-row grid.
            cats = df["band"].cat.categories if hasattr(df["band"], "cat") else pd.unique(df["band"])
            mapping = {c: FILTER_LOOKUP.get(str(c).lower().strip()) for c in cats}
            df["filter_mapped"] = df["band"].map(mapping).astype("category")
            unmapped = df["filter_mapped"].isna()
            if unmapped.any():
                logger.info("Grid %s: dropping %d row(s) in unmapped bands", path.name, int(unmapped.sum()))
                df = df[~unmapped]
                df["filter_mapped"] = df["filter_mapped"].cat.remove_unused_categories()

    bad_time = df["time"] <= min_time
    bad_mag = ~np.isfinite(df["absolute_magnitude"]) | (df["absolute_magnitude"] > max_abs_mag)
    if bad_time.any() or bad_mag.any():
        logger.info(
            "Grid %s: dropping %d row(s) at t<=%g and %d artifact row(s) with M>%g",
            path.name, int(bad_time.sum()), min_time, int((bad_mag & ~bad_time).sum()), max_abs_mag,
        )
        df = df[~(bad_time | bad_mag)]

    if df.empty:
        raise ValueError(f"Grid {path.name} has no usable rows after filtering")

    df = df.reset_index(drop=True)
    df.attrs["name"] = path.name
    df.attrs["distance_mpc"] = distance

    if use_cache:
        _cache_put(key, df)
    logger.info(
        "Loaded %s: %d/%d rows, %d simulations, t=[%.3f, %.2f] d, "
        "M=[%.2f, %.2f], D_L=%s Mpc, %.0f MB in memory",
        path.name, len(df), n_read, df["sample_id"].nunique(),
        df["time"].min(), df["time"].max(),
        df["absolute_magnitude"].min(), df["absolute_magnitude"].max(),
        f"{distance:.0f}" if np.isfinite(distance) else "unknown",
        df.memory_usage(deep=True).sum() / 1e6,
    )
    return df


def clear_cache() -> None:
    """Drop cached grids (they are hundreds of MB each)."""
    _CACHE.clear()
