# Generated by Django 5.2.13 on 2026-08-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnGridAxis',
            fields=[
                ('grid', models.TextField(primary_key=True, serialize=False)),
                ('time_axis', models.BinaryField()),
                ('distance_mpc', models.FloatField()),
                ('n_samples', models.IntegerField()),
                ('n_time', models.IntegerField()),
            ],
            options={
                'db_table': 'kn_grid_axis',
                'ordering': ['distance_mpc'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KnGridLightcurve',
            fields=[
                ('pk', models.CompositePrimaryKey('grid', 'band', 'sample_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('grid', models.TextField()),
                ('band', models.TextField()),
                ('sample_id', models.IntegerField()),
                ('absmag', models.BinaryField()),
            ],
            options={
                'db_table': 'kn_grid_lightcurve',
                'managed': False,
            },
        ),
    ]
