# Generated by Django 4.2.23 on 2025-07-18 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_vetting', '0003_scorefactor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scorefactor',
            old_name='event_candidate_id',
            new_name='event_candidate',
        ),
    ]
