# Generated by Django 4.2.23 on 2025-07-16 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tom_targets', '0026_alter_basetarget_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('basetarget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tom_targets.basetarget')),
                ('healpix', models.BigIntegerField()),
            ],
            bases=('tom_targets.basetarget',),
        ),
    ]
