# Generated by Django 4.2.23 on 2025-07-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trove_targets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='classification',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='mwebv',
            field=models.FloatField(blank=True, null=True, verbose_name='Milky Way E(B-V)'),
        ),
        migrations.AddField(
            model_name='target',
            name='redshift',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
