# Generated by Django 4.2 on 2026-04-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trove_targets', '0002_target_classification_target_mwebv_target_redshift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='healpix',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
