# Generated by Django 4.2 on 2023-08-10 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("custom_code", "0019_cssfieldcredibleregion_treasuremap_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyObservationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facility", models.CharField(max_length=50)),
                ("parameters", models.JSONField()),
                ("observation_id", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=200)),
                ("scheduled_start", models.DateTimeField(null=True)),
                ("scheduled_end", models.DateTimeField(null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "survey_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="custom_code.cssfield",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
