# Generated by Django 4.2 on 2023-08-10 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tom_surveys", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="SurveyField",
                    fields=[
                        (
                            "name",
                            models.CharField(max_length=6, primary_key=True, serialize=False),
                        ),
                        ("ra", models.FloatField()),
                        ("dec", models.FloatField()),
                        ("ecliptic_lng", models.FloatField()),
                        ("ecliptic_lat", models.FloatField()),
                        ("galactic_lng", models.FloatField()),
                        ("galactic_lat", models.FloatField()),
                        ("healpix", models.BigIntegerField()),
                        ("has_reference", models.BooleanField(default=False)),
                        ("adjacent", models.ManyToManyField(to="tom_surveys.surveyfield")),
                    ],
                    options={
                        "ordering": ["name"],
                    },
                ),
            ],
            database_operations=[],  # table already exists, see custom_code/migrations/0020
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="surveyobservationrecord",
                    name="survey_field",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tom_surveys.surveyfield",
                    ),
                ),
            ],
            database_operations=[],  # reusing existing table
        ),
    ]

# doesn't fully work without the following migration (0003)
