# Generated by Django 4.2 on 2023-08-22 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tom_surveys", "0003_auto_20230810_2050"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="surveyobservationrecord",
            options={"ordering": ("-scheduled_start",)},
        ),
    ]
