# Generated by Django 5.2.13 on 2026-06-18 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tom_nonlocalizedevents', '0018_alter_eventlocalization_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreFactor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('event_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tom_nonlocalizedevents.eventcandidate')),
            ],
            options={
                'unique_together': {('event_candidate', 'key')},
            },
        ),
    ]
