# Generated by Django 4.2.23 on 2025-07-15 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_vetting', '0001_initial'),
    ]

    operations = [
    ]
