# Generated by Django 4.2 on 2025-11-18 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('tom_nonlocalizedevents', '0019_merge_20251111_2206'),
        ('candidate_vetting', '0004_rename_event_candidate_id_scorefactor_event_candidate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scorefactor',
            unique_together={('event_candidate', 'key')},
        ),
    ]
