# Generated by Django 5.2.13 on 2026-06-04 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_vetting', '0007_cosmicflows4q3c_hecate1q3c_hecate2q3c_lsdr10southq3c_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lsdr10southtargetmatch',
            table='ls_dr10south_targetmatch',
        ),
        migrations.AlterModelTable(
            name='lsdr9northtargetmatch',
            table='ls_dr9north_targetmatch',
        ),
    ]
