# Generated by Django 5.2.15 on 2026-06-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0009_alter_cosmicflows4targetmatch_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGalaxyQ3C',
        ),
        migrations.DeleteModel(
            name='AsassnQ3C',
        ),
        migrations.DeleteModel(
            name='Cosmicflows4Q3C',
        ),
        migrations.DeleteModel(
            name='DesiDr1Q3C',
        ),
        migrations.DeleteModel(
            name='DesiSpecQ3C',
        ),
        migrations.DeleteModel(
            name='FermiLatQ3C',
        ),
        migrations.DeleteModel(
            name='Gaiadr3VariableQ3C',
        ),
        migrations.DeleteModel(
            name='GladePlusQ3C',
        ),
        migrations.DeleteModel(
            name='GwgcQ3C',
        ),
        migrations.DeleteModel(
            name='Hecate1Q3C',
        ),
        migrations.DeleteModel(
            name='Hecate2Q3C',
        ),
        migrations.DeleteModel(
            name='LsDr10SouthQ3C',
        ),
        migrations.DeleteModel(
            name='LsDr9NorthQ3C',
        ),
        migrations.DeleteModel(
            name='MilliquasQ3C',
        ),
        migrations.DeleteModel(
            name='NedlvsQ3C',
        ),
        migrations.DeleteModel(
            name='Ps1Q3C',
        ),
        migrations.DeleteModel(
            name='RomaBzcatQ3C',
        ),
        migrations.DeleteModel(
            name='Sdss12PhotozQ3C',
        ),
        migrations.DeleteModel(
            name='TnsQ3C',
        ),
        migrations.DeleteModel(
            name='TwomassQ3C',
        ),
        migrations.DeleteModel(
            name='ZtfVarstarQ3C',
        ),
    ]
