# Generated by Django 4.0.4 on 2022-04-26 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tom_targets', '0019_auto_20210811_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetListExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.TextField(blank=True, default='')),
                ('float_value', models.FloatField(blank=True, null=True)),
                ('bool_value', models.BooleanField(blank=True, null=True)),
                ('time_value', models.DateTimeField(blank=True, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tom_targets.targetlist')),
            ],
            options={
                'unique_together': {('target', 'key')},
            },
        ),
    ]
