# Generated by Django 4.0.4 on 2022-04-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0019_auto_20210811_0018'),
        ('custom_code', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='targetlistextra',
            old_name='target',
            new_name='target_list',
        ),
        migrations.AlterUniqueTogether(
            name='targetlistextra',
            unique_together={('target_list', 'key')},
        ),
    ]
