# Generated by Django 3.2.13 on 2022-05-19 19:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0019_auto_20210811_0018'),
        ('custom_code', '0002_rename_target_targetlistextra_target_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidatenumber', models.IntegerField(null=True)),
                ('filename', models.CharField(max_length=128, null=True)),
                ('elongation', models.FloatField(null=True)),
                ('ra', models.FloatField(null=True)),
                ('dec', models.FloatField(null=True)),
                ('fwhm', models.FloatField(null=True)),
                ('snr', models.FloatField(null=True)),
                ('mag', models.FloatField(null=True)),
                ('magerr', models.FloatField(null=True)),
                ('rawfilename', models.CharField(max_length=128, null=True)),
                ('obsdate', models.DateTimeField(default=datetime.datetime.now)),
                ('field', models.CharField(max_length=32, null=True)),
                ('classification', models.IntegerField(null=True)),
                ('cx', models.FloatField(null=True)),
                ('cy', models.FloatField(null=True)),
                ('cz', models.FloatField(null=True)),
                ('htm16id', models.BigIntegerField(null=True)),
                ('mjdmid', models.FloatField(null=True)),
                ('mlscore', models.FloatField(null=True)),
                ('ncombine', models.IntegerField(null=True)),
                ('gladeid', models.IntegerField(null=True)),
                ('exclude', models.IntegerField(null=True)),
                ('target', models.ForeignKey(db_column='targetid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tom_targets.target')),
            ],
            options={
                'db_table': 'candidates',
            },
        ),
    ]
