# Generated by Django 4.1.2 on 2023-04-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0004_alter_candidate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='mlscore_bogus',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='mlscore_real',
            field=models.FloatField(null=True),
        ),
    ]
