# Generated by Django 4.2 on 2023-05-05 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("custom_code", "0007_alter_candidate_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="field",
            field=models.ForeignKey(
                db_column="field",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="custom_code.cssfield",
            ),
        ),
    ]
