# Generated by Django 4.1 on 2023-05-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_code", "0009_cssfieldcredibleregion_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="cssfield", options={"ordering": ["name"]},),
        migrations.AddField(
            model_name="cssfield",
            name="adjacent",
            field=models.ManyToManyField(to="custom_code.cssfield"),
        ),
    ]

# After running this migration, populate the table using the following code:
# import json
# with open('touch.json') as f:
#     lookup = json.load(f)
# for f, adj in lookup.items():
#     field = CSSField.objects.get(name=f)
#     field.adjacent.set(CSSField.objects.filter(name__in=adj))
#     field.save()
