# Generated by Django 4.1 on 2023-05-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_code", "0010_alter_cssfield_options_cssfield_adjacent"),
    ]

    operations = [
        migrations.AddField(
            model_name="cssfieldcredibleregion",
            name="group",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="cssfieldcredibleregion",
            name="rank_in_group",
            field=models.IntegerField(null=True),
        ),
    ]
