# Generated by Django 4.1 on 2023-05-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_code", "0011_cssfieldcredibleregion_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cssfieldcredibleregion",
            name="probability_contained",
            field=models.FloatField(null=True),
        ),
    ]
