# Generated by Django 4.2 on 2023-05-17 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "tom_nonlocalizedevents",
            "0017_alter_eventsequence_external_coincidence_and_more",
        ),
        ("custom_code", "0012_cssfieldcredibleregion_probability_contained"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cssfieldcredibleregion",
            options={"ordering": ["-probability_contained"]},
        ),
        migrations.CreateModel(
            name="CredibleRegionContour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("probability", models.FloatField()),
                ("pixels", models.JSONField()),
                (
                    "localization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tom_nonlocalizedevents.eventlocalization",
                    ),
                ),
            ],
        ),
    ]
