# Generated by Django 4.2 on 2023-05-17 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "tom_nonlocalizedevents",
            "0017_alter_eventsequence_external_coincidence_and_more",
        ),
        ("custom_code", "0013_alter_cssfieldcredibleregion_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credibleregioncontour",
            name="localization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credible_region_contours",
                to="tom_nonlocalizedevents.eventlocalization",
            ),
        ),
        migrations.AddConstraint(
            model_name="credibleregioncontour",
            constraint=models.UniqueConstraint(
                fields=("localization", "probability"),
                name="unique_localization_probability",
            ),
        ),
    ]
