# Generated by Django 4.2 on 2025-11-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0014_alter_credibleregioncontour_localization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credibleregioncontour',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
