# Generated by Django 4.2 on 2023-05-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_code", "0014_alter_credibleregioncontour_localization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cssfield",
            name="has_reference",
            field=models.BooleanField(default=False),
        ),
    ]

# After running this migration, populate the column using the following code:
# from astropy.table import Table
# from custom_code.models import CSSField
# t = Table.read('f.G96.list', format='ascii')
# CSSField.objects.filter(name__in=t['col1']).update(has_reference=True)
