# Generated by Django 4.1 on 2023-06-15 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("custom_code", "0015_cssfield_has_reference"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, null=True, region="US"
                    ),
                ),
                ("test_alerts", models.BooleanField(default=False)),
                ("subthreshold_alerts", models.BooleanField(default=False)),
                ("bbh_alerts", models.BooleanField(default=False)),
                ("ns_alerts", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]

# After running this migration, populate the column using the following code:
# from django.contrib.auth.models import User
# from custom_code.models import Profile
# for user in User.objects.all():
#     Profile(user=user, id=user.id).save()
