# Generated by Django 4.2 on 2023-06-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_code", "0016_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="burst_alerts",
            field=models.BooleanField(default=False),
        ),
    ]
