# Generated by Django 4.2 on 2023-08-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_code", "0015_cssfield_has_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="cssfieldcredibleregion",
            name="first_observable",
            field=models.DateTimeField(null=True),
        ),
    ]
