# Generated by Django 4.2 on 2023-08-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_code", "0018_cssfieldcredibleregion_first_observable"),
    ]

    operations = [
        migrations.AddField(
            model_name="cssfieldcredibleregion",
            name="treasuremap_id",
            field=models.IntegerField(null=True),
        ),
    ]
