# Generated by Django 4.2 on 2023-08-11 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tom_surveys", "0003_auto_20230810_2050"),
        ("custom_code", "0020_cssfieldcredibleregion_observation_record_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidate",
            options={},
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="exclude",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="field",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="gladeid",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="htm16id",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="mjdmid",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="ncombine",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="obsdate",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="rawfilename",
        ),
        migrations.AddField(
            model_name="candidate",
            name="observation_record",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="tom_surveys.surveyobservationrecord",
            ),
        ),
    ]
