# Generated by Django 4.2 on 2023-08-11 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "custom_code",
            "0021_alter_candidate_options_remove_candidate_exclude_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="filename",
        ),
    ]
