# Generated by Django 4.2 on 2023-08-24 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "tom_nonlocalizedevents",
            "0017_alter_eventsequence_external_coincidence_and_more",
        ),
        ("tom_surveys", "0004_alter_surveyobservationrecord_options"),
        (
            "custom_code",
            "0023_remove_cssfieldcredibleregion_unique_localization_css_field_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveyfieldcredibleregion",
            name="treasuremap_id",
        ),
        migrations.AlterField(
            model_name="surveyfieldcredibleregion",
            name="localization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surveyfieldcredibleregions",
                to="tom_nonlocalizedevents.eventlocalization",
            ),
        ),
        migrations.AlterField(
            model_name="surveyfieldcredibleregion",
            name="survey_field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credibleregions",
                to="tom_surveys.surveyfield",
            ),
        ),
    ]
