# Generated by Django 4.2.16 on 2025-01-06 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0024_remove_surveyfieldcredibleregion_treasuremap_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
