ALLOWED_HOST = ''       # hostname or IP address of the web server (leave blank for development)
ATLAS_API_KEY = ''      # API key for the ATLAS forced photometry server
DEBUG = False           # set to True to display error tracebacks in browser, leave False in production
FORCE_SCRIPT_NAME = ''  # the subdomain where you will host the site (leave blank for development)
GCN_CLIENT_ID = ''      # client ID for GCN Classic over Kafka
GCN_CLIENT_SECRET = ''  # secret key for GCN Classic over Kafka
GEM_N_API_KEY = ''      # API key for Gemini Observatory North
GEM_S_API_KEY = ''      # API key for Gemini Observatory South
LCO_API_KEY = ''        # API key for Las Cumbres Observatory
MMT_PROGRAMS = []       # list of (API key, human-readable name) for MMT Observatory
POSTGRES_DB = ''        # name of the Postgres database
POSTGRES_HOST = ''      # hostname or IP address of the Postgres database server
POSTGRES_PASSWORD = ''  # password for the Postgres database
POSTGRES_PORT = 5432    # port number for the Postgres database
POSTGRES_USER = ''      # username for the Postgres database
SCIMMA_AUTH_USERNAME = '' # username for SCIMMA authentication
SCIMMA_AUTH_PASSWORD = '' # password for SCIMMA authentication
SECRET_KEY = ''         # see https://docs.djangoproject.com/en/4.1/ref/settings/#secret-key
TNS_API_KEY = ''        # API key for the Transient Name Server
